### ISSUE TITLE
MPH Switch not working 

### ISSUE THREAD

**Issue by snippy62** [papampi/nvOC_by_fullzero#117]
not to sure what details i need to place hear but the mph switch not working geting this error

LAUNCHING:  SALFTER_MPH_SWITCHING (will launch miner)

python2.7: can't open file '"/home/m1/NVOC/testing/mph_switch"': [Errno 2] No such file or directory

cat: /home/m1/NVOC/testing/current-profit: No such file or directory

mining process in Guake Tab

have confirmed that its not just me geting the error  plz let me know what other info is required 

nvOC_Ver="nvOC v0019-2.1 - Community Release" # Do not edit this
nvOC_1bash_ver="v0019-2.1.0029"   # Do not edit this

**Comment by LuKePicci** [comment]
Could you confirm that "/home/m1/NVOC/testing/mph_switch" exists? Can you see that file if you navigate to that directory?

**Comment by snippy62** [comment]
yes its there in the location thats says it cant open

**Comment by LuKePicci** [comment]
Got it, is fixed in #118.  If you can't wait for this to be merged just remove those extra quotes in the command line. After merge, just update by doing `bash nvOC upgrade` from inside your NVOC/testing directory.

**Comment by snippy62** [comment]
i beleave this is an error on my part and not related but now when i run with new pull i get 

File "/home/m1/NVOC/Testing1/mph_switch", line 123, in <module>
    subprocess.call(("screen -c "+str(output_dir)+"/nvoc_logs/screenlog.0 -dmS miner "+coin).split(" "))
NameError: name 'output_dir' is not defined

it keeps repeating the process with same resalt

**Comment by snippy62** [comment]
i was able to bring up that line in the WTM file im still learning but it looks ok to me 
   
  # launch new miner
  subprocess.call(("screen -c "+str(output_dir)+"/nvoc_logs/screenlog.0 -dmS miner "+coin).split(" "))
