### ISSUE TITLE
MPH Switch: NameError: name 'output_dir' is not defined

### ISSUE THREAD

**Issue by snippy62** [papampi/nvOC_by_fullzero#126]
i beleave this is an error on my part and not related too MPH Switch not working #117 but now  when i run with new pull i get

File "/home/m1/NVOC/Testing1/mph_switch", line 123, in 
subprocess.call(("screen -c "+str(output_dir)+"/nvoc_logs/screenlog.0 -dmS miner "+coin).split(" "))
NameError: name 'output_dir' is not defined

it keeps repeating the process with same resalt

i was able to bring up that line in the WTM file im still learning but it looks ok to me??

launch new miner
subprocess.call(("screen -c "+str(output_dir)+"/nvoc_logs/screenlog.0 -dmS miner "+coin).split(" "))

Software info:
Report ver : v0019-2.1.0012
nvOC path : /home/m1/NVOC/Testing1
nvOC (1bash) : nvOC v0019-2.1 - Community Release
nvOC (3main) : nvOC v0019-2.1 - Community Release
1bash ver : v0019-2.1.0029
3main ver : v0019-2.1.0022
5watchdog ver : v0019-2.1.020
6tempcontrol v: v0019-2.1.0006
wtm switch ver: v0019-2.1.0021
Kernel : 4.4.0-128-generic
OS : Ubuntu 16.04.4 LTS
System : (gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.9)
nvidia driver : 390.67

Hardware info:
Motherboard : Gateway DX4840
BIOS ver. : P01-A4 02/15/2011
CPU Model : Core(TM) i3 CPU 550 @ 3.20GHz
CPU Cores : 4 (Cores + Threads)
Mem Total : 3971400 kB
Mem Free : 2609808 kB
Swap Total : 0 kB
Swap Free : 0 kB
Ethernet : Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 06)

CUDA SDK version
nvcc path : /usr/local/cuda-8.0/bin/nvcc
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61

nvoc.service systemd's log
● nvoc.service - nvOC Service
Loaded: loaded (/etc/systemd/system/nvoc.service; static; vendor preset: enabled)
Active: inactive (dead)

HDD and Partion info:
NAME SIZE FSTYPE TYPE ROTA HOTPLUG TRAN VENDOR MODEL REV MOUNTPOINT
sda 232.9G disk 1 0 sata ATA Hitachi HTS54252 C31P
├─sda1 9M vfat part 1 0
└─sda2 232.9G ext4 part 1 0 /

VGA info:
01:00.0 VGA compatible controller: NVIDIA Corporation Device 1c02 (rev a1)

Local git branch and submodules status:

19-2.1...origin/19-2.1
M 1bash.template
ee963aa25b6b8d4f8299a2d5f13749fc6bdee498 miners (heads/19-2.1)

19-2.1...origin/19-2.1
-cd6fab68823e247bb84dd1fa0448d5f75ec4917d ANXccminer/src
-aafe2d19b6d9eb07d942d70ced3049e9aed1c241 ASccminer/src
-31865e0b846ad98e2ce99aeb9b28bb51d3be22db KTccminer-cryptonight/src
-c5ab73837c8024f1e6b8fe7ad46e6881fb8366e6 KTccminer/src
-7d41d49b92db27b9ab80270adaa92f6b06d1ef78 KXccminer/src
-78dad7dd659eae72a07d2448de62b1946c1f2b41 MSFTccminer/src
-8affcb9cd09edd917d33c1ed450f23400f571bdb NAccminer/src
-9e86bdd24ed7911b698f1d0ef61a4028fcbd13c5 SPccminer/src
c800f1a803e1b2074ed2a7c15023c096d0772048 SUPRminer/src (1.5)
-a81ab0f7a557a12a21d716dd03537bc8633fd176 TPccminer/src
bfd1c002f98f2d63f2174618838afc28cf4ffffe cpuOPT/src (v3.8.8.1)
-48b170a5828256600ca71e66d4c114af4e114236 vertminer/src
c0ab1734332d6472225d8ac7394f6fcba71aabc9 xmr-stak/src (2.4.4)

1bash settings:
1bash version .............: v0019-2.1.0029
LOCAL or REMOTE ...........: LOCAL
TEAMVIEWER started ........: YES
SSH daemon started ........: YES
SLOW_USB_KEY_MODE .........: NO
SRR .......................: NO

Watchdog ..................: YES
SYSRQ Reboot ..............: NO
Watchdog Cycle ............: 15
GPU Utilization Threshold .: 70
Alternate Pool ............: NO

Temp Control ..............: YES
MANUAL_FAN ................: NO
TARGET_TEMP ...............: 65
__FAN_ADJUST ..............: 5
POWER_ADJUST ..............: 5
ALLOWED_TEMP_DIFF .........: 2
RESTORE_POWER_LIMIT .......: 85
MINIMAL_FAN_SPEED .........: 50
MAXIMAL_FAN_SPEED .........: 95

CLEAR_LOGS_ON_BOOT ........: NO
AUTO_UPDATE ...............: STABLE
AUTO_REBOOT ...............: NO
_Parallax_MODE (upPaste)...: NO

TELEGRAM_MESSAGES .: NO
TELEGRAM_ALERTS ...: NO

HEADLESS MODE:.............: NO
GPUPowerMizerMode_Adjust...: NO
ETH Pill ..................: NO

POWERLIMIT MODE ...........: GLOBAL
Power Limit WATTS .........: 130
OVERCLOCK MODE ............: NO

GLOBAL WORKERNAME .........: YES
AUTO WORKERNAME ...........: HOST
WORKERNAME ................: 072
plusCPU ...................: NO

COIN ......................:
ALGO ......................: SKEIN
MINER .....................: TPccminer
ZPOOLPASS .................: hidden_pass...,
WORKER ................:
ADDRESS ...............: ...
POOL ..................:
PORT ..................:
SKEIN INTENSITY ..........: 0

[/code]

**Comment by LuKePicci** [comment]
You should have an auto-geneerated `mph_conf.json` file inside `/home/m1/NVOC/Testing1`, please, let me see its content.
Edit: sorry, found the problem, there is a variable name mispelling.

**Comment by snippy62** [comment]
{
  "output_dir": "/home/m1/NVOC/Testing1",
  "user_name": "Snippy6",
  "miner_name": "snippy6",
  "card_type": "nvidia",
  "currency": "USD",
  "pwrcost": 0.10,
  "min_profit": 0.0,
  "miners":
  {
    "Blake-Vanilla":
    {
      "bin": "/home/m1/NVOC/Testing1/SPccminer/ccminer -a vanilla -o stratum+tcp://{HOST}:{PORT} -u {NAME}.{MINER} -p x",
      "power_limit": 130, "gpu_oc": 0, "mem_oc": 0, "fan": 0,
      "speed": 12.3, "power": 0.389
    },
    "Cryptonight":
    {
      "bin": "/home/m1/NVOC/Testing1/KTccminer-cryptonight/ccminer -o stratum+tcp://{HOST}:{PORT} -u {NAME}.{MINER} -p x",
      "power_limit": 130, "gpu_oc": 0, "mem_oc": 0, "fan": 0,
      "speed": 0.000002, "power": 0.325
    },
    "Equihash":
    {
      "bin": "/home/m1/NVOC/Testing1/zec/v3_4/miner --eexit 3 --fee 0 --pec --server {HOST} --user {NAME}.{MINER} --pass z --port {PORT}",
      "power_limit": 130, "gpu_oc": 0, "mem_oc": 0, "fan": 0,
      "speed": 0.000001140, "power": 0.397
    },
    "Ethash":
    {
      "bin": "/home/m1/NVOC/Testing1/eth/ethminer/latest/ethminer -S {HOST}:{PORT} -O {NAME}.{MINER}:x -U",
      "power_limit": 130, "gpu_oc": 0, "mem_oc": 0, "fan": 0,
      "speed": 0.087, "power": 0.397
    },
    "Groestl":
    {
      "bin": "/home/m1/NVOC/Testing1/SPccminer/ccminer -a groestl -o stratum+tcp://{HOST}:{PORT} -u {NAME}.{MINER} -p x",
      "power_limit": 130, "gpu_oc": 0, "mem_oc": 0, "fan": 0,
      "speed": 0.0853, "power": 0.392
    },
    "Keccak":
    {
      "bin": "/home/m1/NVOC/Testing1/SPccminer/ccminer -a keccak -o stratum+tcp://{HOST}:{PORT} -u {NAME}.{MINER} -p x",
      "power_limit": 130, "gpu_oc": 0, "mem_oc": 0, "fan": 0,
      "speed": 1.45, "power": 0.391
    },
    "Lyra2RE2":
    {
      "bin": "/home/m1/NVOC/Testing1/SPccminer/ccminer -a lyra2v2 -o stratum+tcp://{HOST}:{PORT} -u {NAME}.{MINER} -p x",
      "power_limit": 130, "gpu_oc": 0, "mem_oc": 0, "fan": 0,
      "speed": 0.081, "power": 0.386
    },
    "Myriad-Groestl":
    {
      "bin": "/home/m1/NVOC/Testing1/SPccminer/ccminer -a myr-gr -o stratum+tcp://{HOST}:{PORT} -u {NAME}.{MINER} -p x",
      "power_limit": 130, "gpu_oc": 0, "mem_oc": 0, "fan": 0,
      "speed": 0.158, "power": 0.391
    },
    "NeoScrypt":
    {
      "bin": "/home/m1/NVOC/Testing1/KTccminer/ccminer -a neoscrypt -o stratum+tcp://{HOST}:{PORT} -u {NAME}.{MINER} -p x",
      "power_limit": 130, "gpu_oc": 0, "mem_oc": 0, "fan": 0,
      "speed": 0.002160, "power": 0.397
    },
    "Qubit":
    {
      "bin": "/home/m1/NVOC/Testing1/SPccminer/ccminer -a qubit -o stratum+tcp://{HOST}:{PORT} -u {NAME}.{MINER} -p x",
      "power_limit": 130, "gpu_oc": 0, "mem_oc": 0, "fan": 0,
      "speed": 0.0509, "power": 0.382
    },
    "Scrypt":
    {
      "bin": "/home/m1/NVOC/Testing1/SPccminer/ccminer -a scrypt -o stratum+tcp://{HOST}:{PORT} -u {NAME}.{MINER} -p x",
      "power_limit": 130, "gpu_oc": 0, "mem_oc": 0, "fan": 0,
      "speed": 0.00224, "power": 0.403
    },
    "Sia":
    {
      "bin": "/home/m1/NVOC/Testing1/SPccminer/ccminer -a sia -o stratum+tcp://{HOST}:{PORT} -u {NAME}.{MINER} -p x",
      "power_limit": 130, "gpu_oc": 0, "mem_oc": 0, "fan": 0,
      "speed": 3.700, "power": 0.403
    },
    "Skein":
    {
      "bin": "/home/m1/NVOC/Testing1/ASccminer/ccminer -a skein -o stratum+tcp://{HOST}:{PORT} -u {NAME}.{MINER} -p x",
      "power_limit": 130, "gpu_oc": 0, "mem_oc": 0, "fan": 0,
      "speed": 0.835, "power": 0.383
    },
    "X11":
    {
      "bin": "/home/m1/NVOC/Testing1/TPccminer/ccminer -a x11 -o stratum+tcp://{HOST}:{PORT} -u {NAME}.{MINER} -p x",
      "power_limit": 130, "gpu_oc": 0, "mem_oc": 0, "fan": 0,
      "speed": 0.0327, "power": 0.403
    }
  }
}

**Comment by LuKePicci** [comment]
Fixed in #127
