### ISSUE TITLE
Found error with CPU miner 

### ISSUE THREAD

**Issue by snippy62** [papampi/nvOC_by_fullzero#129]
the built in CPU miner that is mining for xmr is using old algo simple fix was to add  v7 too the end of the algo in the dont know if this was just me or it has been adressed made the change in  3main
      guake -n $HCD -r plusCPU -e "$HCD -a cryptonight -o stratum+tcp://$XMR_POOL:$XMR_PORT -u $XMRADDR -p x -t $threadCOUNT"
    else
      screen -c ${NVOC}/screenrc-miner -dmS plusCPU $HCD -a cryptonight -o stratum+tcp://$XMR_POOL:$XMR_PORT -u $XMRADDR -p x -t $threadCOUNT

and change too 

      guake -n $HCD -r plusCPU -e "$HCD -a cryptonightv7 -o stratum+tcp://$XMR_POOL:$XMR_PORT -u $XMRADDR -p x -t $threadCOUNT"
    else
      screen -c ${NVOC}/screenrc-miner -dmS plusCPU $HCD -a cryptonightv7 -o stratum+tcp://$XMR_POOL:$XMR_PORT -u $XMRADDR -p x -t $threadCOUNT

**Comment by LuKePicci** [comment]
Just to be clear, is this related to old 2.0 or 2.1? Please add the correct label to this issue, there are two with nvOC version number.

**Comment by papampi** [comment]
Thanks for heads up, Added v7 and fixed in https://github.com/papampi/nvOC_by_fullzero_Community_Release/commit/af019b8123e89cc902a97280bd93bfa61d0e1180

**Comment by snippy62** [comment]
it was for the new 2.1 sorry for the lack of info
