### ISSUE TITLE
Still unable to run MPH: wrong path to miners

### ISSUE THREAD

**Issue by snippy62** [papampi/nvOC_by_fullzero#132]
so when i try to run MPH im now not geting any errors and its running a repeat loop checking most profitable but without ever running a miner. did a little pokeing aroung and might have found the issue with the mph_conf.json file it looks like all the miner exacutexe try and run from home/m1/NVOC/Testing1/KTccminer/ccminer when in fact they should run from a folder miners after the Testing1 directory home/m1/NVOC/Testing1/minersKTccminer/ccminer this may not be the problem just somthing that i observed 

Copy of my miner Location 
/home/m1/NVOC/Testing1/miners/SPccminer/ccminer

Copy of my  mph_conf.json (removed my user name and miner name )
{
  "output_dir": "/home/m1/NVOC/Testing1",
  "user_name": "*********",
  "miner_name": "*******",
  "card_type": "nvidia",
  "currency": "USD",
  "pwrcost": 0.10,
  "min_profit": 0.0,
  "miners":
  {
    "Blake-Vanilla":
    {
      "bin": "/home/m1/NVOC/Testing1/SPccminer/ccminer -a vanilla -o stratum+tcp://{HOST}:{PORT} -u {NAME}.{MINER} -p x",
      "power_limit": [200,90], "gpu_oc": [70,40], "mem_oc": [150,0], "fan": 0,
      "speed": 12.3, "power": 0.389
    },
    "Cryptonight":
    {
      "bin": "/home/m1/NVOC/Testing1/KTccminer-cryptonight/ccminer -o stratum+tcp://{HOST}:{PORT} -u {NAME}.{MINER} -p x",
      "power_limit": [200,90], "gpu_oc": [70,40], "mem_oc": [150,0], "fan": 0,
      "speed": 0.000002, "power": 0.325
    },
    "Equihash":
    {
      "bin": "/home/m1/NVOC/Testing1/zec/v3_4/miner --eexit 3 --fee 0 --pec --server {HOST} --user {NAME}.{MINER} --pass z --port {PORT}",
      "power_limit": [200,90], "gpu_oc": [70,40], "mem_oc": [150,0], "fan": 0,
      "speed": 0.000001140, "power": 0.397
    },
    "Ethash":
    {
      "bin": "/home/m1/NVOC/Testing1/eth/ethminer/latest/ethminer -S {HOST}:{PORT} -O {NAME}.{MINER}:x -U",
      "power_limit": [200,90], "gpu_oc": [70,40], "mem_oc": [150,0], "fan": 0,
      "speed": 0.087, "power": 0.397
    },
    "Groestl":
    {
      "bin": "/home/m1/NVOC/Testing1/SPccminer/ccminer -a groestl -o stratum+tcp://{HOST}:{PORT} -u {NAME}.{MINER} -p x",
      "power_limit": [200,90], "gpu_oc": [70,40], "mem_oc": [150,0], "fan": 0,
      "speed": 0.0853, "power": 0.392
    },
    "Keccak":
    {
      "bin": "/home/m1/NVOC/Testing1/SPccminer/ccminer -a keccak -o stratum+tcp://{HOST}:{PORT} -u {NAME}.{MINER} -p x",
      "power_limit": [200,90], "gpu_oc": [70,40], "mem_oc": [150,0], "fan": 0,
      "speed": 1.45, "power": 0.391
    },
    "Lyra2RE2":
    {
      "bin": "/home/m1/NVOC/Testing1/SPccminer/ccminer -a lyra2v2 -o stratum+tcp://{HOST}:{PORT} -u {NAME}.{MINER} -p x",
      "power_limit": [200,90], "gpu_oc": [70,40], "mem_oc": [150,0], "fan": 0,
      "speed": 0.081, "power": 0.386
    },
    "Myriad-Groestl":
    {
      "bin": "/home/m1/NVOC/Testing1/SPccminer/ccminer -a myr-gr -o stratum+tcp://{HOST}:{PORT} -u {NAME}.{MINER} -p x",
      "power_limit": [200,90], "gpu_oc": [70,40], "mem_oc": [150,0], "fan": 0,
      "speed": 0.158, "power": 0.391
    },
    "NeoScrypt":
    {
      "bin": "/home/m1/NVOC/Testing1/KTccminer/ccminer -a neoscrypt -o stratum+tcp://{HOST}:{PORT} -u {NAME}.{MINER} -p x",
      "power_limit": [200,90], "gpu_oc": [70,40], "mem_oc": [150,0], "fan": 0,
      "speed": 0.002160, "power": 0.397
    },
    "Qubit":
    {
      "bin": "/home/m1/NVOC/Testing1/SPccminer/ccminer -a qubit -o stratum+tcp://{HOST}:{PORT} -u {NAME}.{MINER} -p x",
      "power_limit": [200,90], "gpu_oc": [70,40], "mem_oc": [150,0], "fan": 0,
      "speed": 0.0509, "power": 0.382
    },
    "Scrypt":
    {
      "bin": "/home/m1/NVOC/Testing1/SPccminer/ccminer -a scrypt -o stratum+tcp://{HOST}:{PORT} -u {NAME}.{MINER} -p x",
      "power_limit": [200,90], "gpu_oc": [70,40], "mem_oc": [150,0], "fan": 0,
      "speed": 0.00224, "power": 0.403
    },
    "Sia":
    {
      "bin": "/home/m1/NVOC/Testing1/SPccminer/ccminer -a sia -o stratum+tcp://{HOST}:{PORT} -u {NAME}.{MINER} -p x",
      "power_limit": [200,90], "gpu_oc": [70,40], "mem_oc": [150,0], "fan": 0,
      "speed": 3.700, "power": 0.403
    },
    "Skein":
    {
      "bin": "/home/m1/NVOC/Testing1/ASccminer/ccminer -a skein -o stratum+tcp://{HOST}:{PORT} -u {NAME}.{MINER} -p x",
      "power_limit": [200,90], "gpu_oc": [70,40], "mem_oc": [150,0], "fan": 0,
      "speed": 0.835, "power": 0.383
    },
    "X11":
    {
      "bin": "/home/m1/NVOC/Testing1/TPccminer/ccminer -a x11 -o stratum+tcp://{HOST}:{PORT} -u {NAME}.{MINER} -p x",
      "power_limit": [200,90], "gpu_oc": [70,40], "mem_oc": [150,0], "fan": 0,
      "speed": 0.0327, "power": 0.403
    }
  }
}

[code]

Software info:
Report ver    :  v0019-2.1.0012
nvOC path     :  /home/m1/NVOC/Testing1
nvOC (1bash)  :  nvOC v0019-2.1 - Community Release
nvOC (3main)  :  nvOC v0019-2.1 - Community Release   
1bash ver     :  v0019-2.1.0030
3main ver     :  v0019-2.1.0023                  
5watchdog ver :  v0019-2.1.020   
6tempcontrol v:  v0019-2.1.0006   
wtm switch ver:  v0019-2.1.0021   
Kernel        :  4.4.0-128-generic
OS            :  Ubuntu 16.04.4 LTS
System        :  (gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.9)
nvidia driver :  390.67

Hardware info:
Motherboard   :  Gateway DX4840          
BIOS ver.     :  P01-A4         02/15/2011
CPU Model     :  Core(TM) i3 CPU         550  @ 3.20GHz
CPU Cores     :  4 (Cores + Threads)
Mem Total     :         3971404 kB
Mem Free      :         1984452 kB
Swap Total    :               0 kB
Swap Free     :               0 kB
Ethernet      :  Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 06)

CUDA SDK version
nvcc path     : /usr/local/cuda-8.0/bin/nvcc
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61

nvoc.service systemd's log
● nvoc.service - nvOC Service
   Loaded: loaded (/etc/systemd/system/nvoc.service; static; vendor preset: enabled)
   Active: inactive (dead)

HDD and Partion info:
NAME     SIZE FSTYPE TYPE ROTA HOTPLUG TRAN   VENDOR   MODEL             REV MOUNTPOINT
sda    232.9G        disk    1       0 sata   ATA      Hitachi HTS54252 C31P 
├─sda1     9M vfat   part    1       0                                       /media/m1/12D3-A8691
└─sda2 232.9G ext4   part    1       0                                       /

VGA info:
01:00.0 VGA compatible controller: NVIDIA Corporation Device 1c02 (rev a1)
03:00.0 VGA compatible controller: NVIDIA Corporation GM206 [GeForce GTX 960] (rev a1)

Local git branch and submodules status:
## 19-2.1...origin/19-2.1
+239b91c350c3341ee38239b2b8277524cdde80f2 miners (remotes/origin/19-2.1)
## HEAD (no branch)
 cd6fab68823e247bb84dd1fa0448d5f75ec4917d ANXccminer/src (heads/master)
 aafe2d19b6d9eb07d942d70ced3049e9aed1c241 ASccminer/src (1.5.3-tpruvot-81-gaafe2d1)
 31865e0b846ad98e2ce99aeb9b28bb51d3be22db KTccminer-cryptonight/src (2.06)
 c5ab73837c8024f1e6b8fe7ad46e6881fb8366e6 KTccminer/src (1.4.6-tpruvot-1293-gc5ab738)
 7d41d49b92db27b9ab80270adaa92f6b06d1ef78 KXccminer/src (0.1)
 78dad7dd659eae72a07d2448de62b1946c1f2b41 MSFTccminer/src (2.2.5-rvn)
 8affcb9cd09edd917d33c1ed450f23400f571bdb NAccminer/src (v2.2-mod-r2)
 9e86bdd24ed7911b698f1d0ef61a4028fcbd13c5 SPccminer/src (1.5.81)
 c800f1a803e1b2074ed2a7c15023c096d0772048 SUPRminer/src (1.5)
 a81ab0f7a557a12a21d716dd03537bc8633fd176 TPccminer/src (2.2.5-tpruvot)
-bfd1c002f98f2d63f2174618838afc28cf4ffffe cpuOPT/src
+3042aa21bedf15d9b9333750331d317705e2118d vertminer/src (v1.0-beta.1-4-g3042aa2)
 c0ab1734332d6472225d8ac7394f6fcba71aabc9 xmr-stak/src (2.4.4)

1bash settings:
1bash version .............: v0019-2.1.0030
LOCAL or REMOTE ...........: LOCAL
TEAMVIEWER started ........: YES
SSH daemon started ........: YES
SLOW_USB_KEY_MODE .........: NO
SRR .......................: NO

Watchdog ..................: YES
SYSRQ Reboot ..............: NO
Watchdog Cycle ............: 15
GPU Utilization Threshold .: 70
Alternate Pool ............: NO

Temp Control ..............: YES
MANUAL_FAN ................: NO
TARGET_TEMP ...............: 65
__FAN_ADJUST ..............: 5
POWER_ADJUST ..............: 5
ALLOWED_TEMP_DIFF .........: 2
RESTORE_POWER_LIMIT .......: 85
MINIMAL_FAN_SPEED .........: 50
MAXIMAL_FAN_SPEED .........: 95

CLEAR_LOGS_ON_BOOT ........: NO
AUTO_UPDATE ...............: STABLE
AUTO_REBOOT ...............: NO
_Parallax_MODE (upPaste)...: NO

TELEGRAM_MESSAGES .: NO
TELEGRAM_ALERTS ...: NO

HEADLESS MODE:.............: NO
GPUPowerMizerMode_Adjust...: NO
ETH Pill ..................: NO

POWERLIMIT MODE ...........: GPU_SPECIFIC
GPU0 Power Limit ..........: 200
GPU1 Power Limit ..........: 90
OVERCLOCK MODE ............: GPU_SPECIFIC
GPU0 Core Overclock ........: 70
GPU0 Memory Overclock ......: 150
GPU1 Core Overclock ........: 40
GPU1 Memory Overclock ......: 0

GLOBAL WORKERNAME .........: YES
AUTO WORKERNAME ...........: CUSTOM
WORKERNAME ................: Snippy6
plusCPU ...................: NO

COIN ......................: 
ALGO ......................: CRYPTONIGHTHEAVY
MINER .....................: xmr-stak
ZPOOLPASS .................: hidden_pass...,
WORKER ................:
ADDRESS ...............: ...
POOL ..................:
PORT ..................:
CRYPTONIGHTHEAVY INTENSITY ..........: 0

[/code]
one other thing i just noticed might be related when i ran for the reprot there is a protion of the Local git branch and submodules status: that is red........  origin/19-2.1 and HEAD (no branch) are both in red

**Comment by LuKePicci** [comment]
Is is exactly a path problem, in 2.1 miners have been moved but nobody took care of relocating those paths inside salfter's switchers. As you can see nobody complained yet about mph_switch issues because lack of testers. Thank you so much for reporting, hopefully we are getting closer.

The git status (compact) output you see in red is because miners submodule, and all its sources submodules are checked out in detached state, which means your local tree is not considered as being part of a branch. Do not care about that, it is normal for a git submodule to be in this state.
