### ISSUE TITLE
WTM_top_coin file not found on first switcher run

### ISSUE THREAD

**Issue by snippy62** [papampi/nvOC_by_fullzero#138]
When trying to run WTM_SWITCHING i get this error 
I think maybe WTM_top_coin file name switched to current-profit. I could be wrong i did reinstall from git and was able to reprodue the same error 

WhatToMine.com Auto Switch v0019-2.1.0021 by papampi

/home/m1/NVOC/test2/8wtm_auto_switch: line 83: /home/m1/NVOC/test2/WTM_top_coin: No such file or directory
Miner not running

Miner still not running, waiting ...

Miner still not running, waiting ...

Miner still not running, waiting ...

Check last top coin and change if not in coin list any more
FIRST_COIN="$(echo "$WTM_AUTO_SWITCH_COINS" | awk -F'[_;]' '{print $1}')"
TOP_COIN=$(sed 's/:[0-9]*//' < ${NVOC}/WTM_top_coin)
if [ ! $(echo "$WTM_AUTO_SWITCH_COINS" | grep "$TOP_COIN") ]
then
  echo "Last top coin not in current coin list any more, Switch to 1st coin"
  echo " " > ${NVOC}/WTM_top_coin
  echo "$FIRST_COIN:100" > ${NVOC}/WTM_top_coin

**Comment by LuKePicci** [comment]
You always see that error on first run I think. The file name is still WTM_top_coin. Does it switches fine after that?

**Comment by papampi** [comment]
On first run it creates and add top coin to WTM_top_coin, after that it should be ok

**Comment by papampi** [comment]
Should be fixed in #140
