### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by snippy62** [papampi/nvOC_by_fullzero#141]
fresh pull and geting this error in 0miner
   
/home/m1/NVOC/mining/0miner: line 176: syntax error near unexpected token `elif'
/home/m1/NVOC/mining/0miner: line 176: `  elif [[ $EQUIHASH_MINER == BMINER ]]'

**Comment by papampi** [comment]
Should be fixed in https://github.com/papampi/nvOC_by_fullzero_Community_Release/commit/c860f4f16fa993a3f3344e35c82200287e0787e1

**Comment by snippy62** [comment]
your fix did work ty
