### ISSUE TITLE
defalt for cpu miner wrong 

### ISSUE THREAD

**Issue by snippy62** [papampi/nvOC_by_fullzero#144]
when trying to run the CPU miner it tryes to launch it from
 /home/m1/NVOC/mining/cpuOPT/cpuminer 
when it should be
 /home/m1/NVOC/mining/miners/cpuOPT/cpuminer
just changed the 0miner to be 
HCD="${NVOC}/miners/cpuOPT/cpuminer"
from
HCD="${NVOC}/cpuOPT/cpuminer"

**Comment by LuKePicci** [comment]
Could you fill in a PR for that? If I make a PR for this then we have to wait for a reviewer before merge, if you do it I can review and merge immediately.

**Comment by snippy62** [comment]
Do i pull on "release" or "19-2.1"

**Comment by LuKePicci** [comment]
The latter, release is not a development branch

Inviato dal mio dispositivo Windows 10

Da: snippy62
Inviato: martedì 17 luglio 2018 08:11
A: papampi/nvOC_by_fullzero_Community_Release
Cc: Luca Piccirillo; Comment
Oggetto: Re: [papampi/nvOC_by_fullzero_Community_Release] defalt for cpu minerwrong (#144)

Do i pull on "release" or "19-2.1"

**Comment by papampi** [comment]
Fixed in https://github.com/papampi/nvOC_by_fullzero_Community_Release/commit/c296fdea446dd95eecd0f202b2649193a27949bb
