### ISSUE TITLE
OC & PL settings for UNDEFINED algo always apply when salfter auto switcher in use

### ISSUE THREAD

**Issue by snippy62** [papampi/nvOC_by_fullzero#156]
when running the MPH switcher for the over clock i have set to algo specific like suggested i can see in my terminal window that it applies the value but when the switcher starts it resets the value to 0 unsure if i have made an error somewhere  this is the log that made me be leave it was an issue with the switcher also i do have my power set to 150 so dont know why it reverts back to 100 aswell

LAUNCHING:  WTM PROFIT CHECK 

Auto Start Miner Set to YES

  Attribute 'GPUGraphicsClockOffset' (m1-desktop:0[gpu:0]) assigned value 150.

  Attribute 'GPUMemoryTransferRateOffset' (m1-desktop:0[gpu:0]) assigned value 400.

LAUNCHING:  MINER WATCHDOG (LOCAL)

process in screen wdog, guake terminal Tab (f12), 'nvOC wdog-log'

LAUNCHING:  SALFTER_MPH_SWITCHING (will launch miner)

Power limit for GPU 00000000:01:00.0 was set to 100.00 W from 150.00 W.

Warning: persistence mode is disabled on this device. This settings will go back to default as soon as driver unloads (e.g. last application like nvidia-smi or cuda application terminates). Run with [--help | -h] switch to get more information on how to enable persistence mode.

All done.

  Attribute 'GPUGraphicsClockOffset' (m1-desktop:0[gpu:0]) assigned value 0.

  Attribute 'GPUGraphicsClockOffset' (m1-desktop:0[gpu:0]) assigned value 0.

  Attribute 'GPUMemoryTransferRateOffset' (m1-desktop:0[gpu:0]) assigned value 0.

  Attribute 'GPUMemoryTransferRateOffset' (m1-desktop:0[gpu:0]) assigned value 0.

ethereum (Ethash): 0.00026278 BTC/day (2.03 USD/day)
ethereum-classic (Ethash): 0.00024685 BTC/day (1.90 USD/day)
musicoin (Ethash): 0.00020619 BTC/day (1.59 USD/day)
digibyte-skein (Skein): 0.00019015 BTC/day (1.47 USD/day)
expanse (Ethash): 0.00017562 BTC/day (1.35 USD/day)

**Comment by papampi** [comment]
May be it's getting vallues from other algo specific settings, can you make some changes to uppercase algo specific values and see how it goes.
Make cahnges with identifiable values, like if you have for lower case eth OC 100 make it for uppercase 101

**Comment by LuKePicci** [comment]
Please check if correct clocks appear in the auto-generated mph_conf.json.

________________________________
Da: snippy62 <notifications@github.com>
Inviato: Monday, July 23, 2018 12:41:30 PM
A: papampi/nvOC_by_fullzero_Community_Release
Cc: Subscribed
Oggetto: [papampi/nvOC_by_fullzero_Community_Release] MPH switcher (#156)


when running the MPH switcher for the over clock i have set to algo specific like suggested i can see in my terminal window that it applies the value but when the switcher starts it resets the value to 0 unsure if i have made an error somewhere this is the log that made me be leave it was an issue with the switcher also i do have my power set to 150 so dont know why it reverts back to 100 aswell

LAUNCHING: WTM PROFIT CHECK

Auto Start Miner Set to YES

Attribute 'GPUGraphicsClockOffset' (m1-desktop:0[gpu:0]) assigned value 150.

Attribute 'GPUMemoryTransferRateOffset' (m1-desktop:0[gpu:0]) assigned value 400.

LAUNCHING: MINER WATCHDOG (LOCAL)

process in screen wdog, guake terminal Tab (f12), 'nvOC wdog-log'

LAUNCHING: SALFTER_MPH_SWITCHING (will launch miner)

Power limit for GPU 00000000:01:00.0 was set to 100.00 W from 150.00 W.

Warning: persistence mode is disabled on this device. This settings will go back to default as soon as driver unloads (e.g. last application like nvidia-smi or cuda application terminates). Run with [--help | -h] switch to get more information on how to enable persistence mode.

All done.

Attribute 'GPUGraphicsClockOffset' (m1-desktop:0[gpu:0]) assigned value 0.

Attribute 'GPUGraphicsClockOffset' (m1-desktop:0[gpu:0]) assigned value 0.

Attribute 'GPUMemoryTransferRateOffset' (m1-desktop:0[gpu:0]) assigned value 0.

Attribute 'GPUMemoryTransferRateOffset' (m1-desktop:0[gpu:0]) assigned value 0.

ethereum (Ethash): 0.00026278 BTC/day (2.03 USD/day)
ethereum-classic (Ethash): 0.00024685 BTC/day (1.90 USD/day)
musicoin (Ethash): 0.00020619 BTC/day (1.59 USD/day)
digibyte-skein (Skein): 0.00019015 BTC/day (1.47 USD/day)
expanse (Ethash): 0.00017562 BTC/day (1.35 USD/day)

**Comment by LuKePicci** [comment]
@snippy62 I hope to receive some feedback from you after applying latest patch.

**Comment by snippy62** [comment]
sorry was away for the morning i havent updated yet my mph .jason file has in
  },
    "Ethash":
    {
      "bin": "/home/m1/NVOC/mining/miners/ethminer/latest/ethminer -S {HOST}:{PORT} -O {NAME}.{MINER}:x -U",
      "power_limit": 100, "gpu_oc": 0, "mem_oc": 0, "fan": 0,
      "speed": 0.087, "power": 0.397
    },

so it was useing the setting from the .json file i will let u know after i pull merged the new resalt
