### ISSUE TITLE
mph_conf.json decode failure

### ISSUE THREAD

**Issue by snippy62** [papampi/nvOC_by_fullzero#161]
LAUNCHING:  MINER WATCHDOG (LOCAL)

process in screen wdog, guake terminal Tab (f12), 'nvOC wdog-log'

LAUNCHING:  SALFTER_MPH_SWITCHING (will launch miner)

 2152 pts/25   S+     0:00 tail -n 0 -f /home/m1/NVOC/mining/nvoc_logs/screenlog.0
mining process in Guake Tab

Traceback (most recent call last):
  File "/home/m1/NVOC/mining/mph_switch", line 14, in <module>
    cfg=json.loads(open(sys.argv[1]).read())
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

ethereum (Ethash): 0.00025662 BTC/day (2.10 USD/day)
monacoin (Lyra2RE2): 0.00023514 BTC/day (1.93 USD/day)
ethereum-classic (Ethash): 0.00023106 BTC/day (1.89 USD/day)
musicoin (Ethash): 0.00020873 BTC/day (1.71 USD/day)

**Comment by LuKePicci** [comment]
It says: "No JSON object could be decoded" so I would like to see mph_conf.json contents

Please attach also 1bash contents, not here, upload it on pastebin

**Comment by LuKePicci** [comment]
By intuition, may be something is going wrong with OC settings. Nothing has changed from previous versions that can cause such an error.

**Comment by papampi** [comment]
I used to get something similar when it couldnt get BTC value

**Comment by LuKePicci** [comment]
Yeah, this happens when the string he expects to be a valid JSON it is not. At line 14 of mph_switch it try to load mph_conf.json. 

Any param below I highlited in bold can be the culprit:

{
  "output_dir": "${NVOC}",
  "user_name": "$MPH_USERNAME",
  "miner_name": "$WORKER_NAME",
  "card_type": "nvidia",
  "currency": "$CURRENCY",
  "pwrcost": **$POWER_COST**,
  "min_profit": **$MINIMUM_PROFIT,**
  "miners":
  {
    "Blake-Vanilla":
    {
      "bin": "${NVOC}/miners/SPccminer/ccminer -a vanilla -o stratum+tcp://{HOST}:{PORT} -u {NAME}.{MINER} -p x",
      "power_limit": **$pwr_lim_blake_vanilla**, "gpu_oc": **$gpu_clks_blake_vanilla**, "mem_oc": **$mem_clks_blake_vanilla**, "fan": 0,
      "speed": 12.3, "power": 0.389
    },
 …
}
or any equivalent for other algos.

**Comment by snippy62** [comment]
hear is my mph_conf.json file 
also i didn't change my over clock at all i preformed "bash nvOC upgrade"well running when done i closed off terminal and reopened it 
{
  "output_dir": "/home/m1/NVOC/mining",
  "user_name": "Snippy6",
  "miner_name": "Snippy6",
  "card_type": "nvidia",
  "currency": "USD",
  "pwrcost": 0.10,
  "min_profit": 0.0,
  "miners":
  {
    "Blake-Vanilla":
    {
      "bin": "/home/m1/NVOC/mining/miners/SPccminer/ccminer -a vanilla -o stratum+tcp://{HOST}:{PORT} -u {NAME}.{MINER} -p x",
      "power_limit": , "gpu_oc": , "mem_oc": , "fan": 0,
      "speed": 12.3, "power": 0.389
    },
    "Cryptonight-Monero":
    {
      "bin": "/home/m1/NVOC/mining/miners/xmr-stak/xmr-stak_miner --currency monero7 --noCPU --noAMD -o {HOST}:{PORT} -u {NAME}.{MINER} -p x -i 0",
      "power_limit": , "gpu_oc": , "mem_oc": , "fan": 0,
      "speed": 0.000002, "power": 0.325
    },
    "Equihash":
    {
      "bin": "/home/m1/NVOC/mining/miners/ewbf/3_4/miner --eexit 3 --fee 0 --pec --server {HOST} --user {NAME}.{MINER} --pass z --port {PORT}",
      "power_limit": , "gpu_oc": , "mem_oc": , "fan": 0,
      "speed": 0.000001140, "power": 0.397
    },
    "Ethash":
    {
      "bin": "/home/m1/NVOC/mining/miners/ethminer/latest/ethminer -S {HOST}:{PORT} -O {NAME}.{MINER}:x -U",
      "power_limit": 100, "gpu_oc": 0, "mem_oc": 0, "fan": 0,
      "speed": 0.087, "power": 0.397
    },
    "Groestl":
    {
      "bin": "/home/m1/NVOC/mining/miners/SPccminer/ccminer -a groestl -o stratum+tcp://{HOST}:{PORT} -u {NAME}.{MINER} -p x",
      "power_limit": , "gpu_oc": , "mem_oc": , "fan": 0,
      "speed": 0.0853, "power": 0.392
    },
    "Keccak":
    {
      "bin": "/home/m1/NVOC/mining/miners/SPccminer/ccminer -a keccak -o stratum+tcp://{HOST}:{PORT} -u {NAME}.{MINER} -p x",
      "power_limit": , "gpu_oc": , "mem_oc": , "fan": 0,
      "speed": 1.45, "power": 0.391
    },
    "Lyra2RE2":
    {
      "bin": "/home/m1/NVOC/mining/miners//SPccminer/ccminer -a lyra2v2 -o stratum+tcp://{HOST}:{PORT} -u {NAME}.{MINER} -p x",
      "power_limit": , "gpu_oc": , "mem_oc": , "fan": 0,
      "speed": 0.081, "power": 0.386
    },
    "Myriad-Groestl":
    {
      "bin": "/home/m1/NVOC/mining/miners/SPccminer/ccminer -a myr-gr -o stratum+tcp://{HOST}:{PORT} -u {NAME}.{MINER} -p x",
      "power_limit": , "gpu_oc": , "mem_oc": , "fan": 0,
      "speed": 0.158, "power": 0.391
    },
    "NeoScrypt":
    {
      "bin": "/home/m1/NVOC/mining/miners/KTccminer/ccminer -a neoscrypt -o stratum+tcp://{HOST}:{PORT} -u {NAME}.{MINER} -p x",
      "power_limit": , "gpu_oc": , "mem_oc": , "fan": 0,
      "speed": 0.002160, "power": 0.397
    },
    "Qubit":
    {
      "bin": "/home/m1/NVOC/mining/miners/SPccminer/ccminer -a qubit -o stratum+tcp://{HOST}:{PORT} -u {NAME}.{MINER} -p x",
      "power_limit": , "gpu_oc": , "mem_oc": , "fan": 0,
      "speed": 0.0509, "power": 0.382
    },
    "Scrypt":
    {
      "bin": "/home/m1/NVOC/mining/miners/SPccminer/ccminer -a scrypt -o stratum+tcp://{HOST}:{PORT} -u {NAME}.{MINER} -p x",
      "power_limit": , "gpu_oc": , "mem_oc": , "fan": 0,
      "speed": 0.00224, "power": 0.403
    },
    "Sia":
    {
      "bin": "/home/m1/NVOC/mining/miners/SPccminer/ccminer -a sia -o stratum+tcp://{HOST}:{PORT} -u {NAME}.{MINER} -p x",
      "power_limit": , "gpu_oc": , "mem_oc": , "fan": 0,
      "speed": 3.700, "power": 0.403
    },
    "Skein":
    {
      "bin": "/home/m1/NVOC/mining/miners/ASccminer/ccminer -a skein -o stratum+tcp://{HOST}:{PORT} -u {NAME}.{MINER} -p x",
      "power_limit": , "gpu_oc": , "mem_oc": , "fan": 0,
      "speed": 0.835, "power": 0.383
    },
    "X11":
    {
      "bin": "/home/m1/NVOC/mining/miners/TPccminer/ccminer -a x11 -o stratum+tcp://{HOST}:{PORT} -u {NAME}.{MINER} -p x",
      "power_limit": , "gpu_oc": , "mem_oc": , "fan": 0,
      "speed": 0.0327, "power": 0.403
    }
  }
}

**Comment by LuKePicci** [comment]
Got it, will fix asap. Just to make sure, I would like to see your 1bash settings also, please share on pastebin.

**Comment by LuKePicci** [comment]
Probably you are using simple ALGO_SPECIFIC OC without having specified oc values for all other algos, will do something to default all those to globals like has already been done for WTM_SWITCHING and NO switching.

**Comment by snippy62** [comment]
https://pastebin.com/AUkwVr2X

**Comment by LuKePicci** [comment]
Thank you very much, I see you have all needed settings so I found what was wrong. The fix is ready, a new PR is on its way.

**Comment by LuKePicci** [comment]
@snippy62 are you fine with testing latest patches from my branch? I would like to get the fix tested before merging.

You should do:
git remote set-branches origin '*'
git fetch
git checkout LuKePicci-19-2.1_salfters_undefined_oc

**Comment by snippy62** [comment]
yes for sure

**Comment by snippy62** [comment]
it did work but im still running into the problem of over clock ive set my oc to be 150 and 1400 in my 1 bash in all location I can see to edit I can see when launching it applys the oc than in another spot after the miner launches that it resets to 0

Auto Start Miner Set to YES


  Attribute 'GPUGraphicsClockOffset' (m1-desktop:0[gpu:0]) assigned value 150.

  Attribute 'GPUMemoryTransferRateOffset' (m1-desktop:0[gpu:0]) assigned value 400.

LAUNCHING:  MINER WATCHDOG (LOCAL)

process in screen wdog, guake terminal Tab (f12), 'nvOC wdog-log'

LAUNCHING:  SALFTER_MPH_SWITCHING (will launch miner)

 2152 pts/25   S+     0:00 tail -n 0 -f /home/m1/NVOC/mining/nvoc_logs/screenlog.0
mining process in Guake Tab

Power limit for GPU 00000000:01:00.0 was set to 100.00 W from 150.00 W.

Warning: persistence mode is disabled on this device. This settings will go back to default as soon as driver unloads (e.g. last application like nvidia-smi or cuda application terminates). Run with [--help | -h] switch to get more information on how to enable persistence mode.

All done.

  Attribute 'GPUGraphicsClockOffset' (m1-desktop:0[gpu:0]) assigned value 0.

  Attribute 'GPUGraphicsClockOffset' (m1-desktop:0[gpu:0]) assigned value 0.

  Attribute 'GPUMemoryTransferRateOffset' (m1-desktop:0[gpu:0]) assigned value 0.

  Attribute 'GPUMemoryTransferRateOffset' (m1-desktop:0[gpu:0]) assigned value 0.


ethereum (Ethash): 0.00025666 BTC/day (2.08 USD/day)
ethereum-classic (Ethash): 0.00022049 BTC/day (1.79 USD/day)
musicoin (Ethash): 0.00021177 BTC/day (1.72 USD/day)
expanse (Ethash): 0.00019330 BTC/day (1.57 USD/day)
monero (Cryptonight-Monero): 0.00012938 BTC/day (

**Comment by snippy62** [comment]
just thinking has to do with what u were just fixing or the same area anyway

**Comment by LuKePicci** [comment]
Check again you mph_conf.json, you should have values for each algo, if you see any 0 check the related setting. The second setting with value 0, should be related to a different algo.

**Comment by snippy62** [comment]
its still being created as 0 for a lot of them i tryed to del the file and let it recreate it with no luck


  "output_dir": "/home/m1/NVOC/mining",
  "user_name": "Snippy6",
  "miner_name": "Snippy6",
  "card_type": "nvidia",
  "currency": "USD",
  "pwrcost": 0.04,
  "min_profit": 0.0,
  "miners":
  {
    "Blake-Vanilla":
    {
      "bin": "/home/m1/NVOC/mining/miners/SPccminer/ccminer -a vanilla -o stratum+tcp://{HOST}:{PORT} -u {NAME}.{MINER} -p x",
      "power_limit": 100, "gpu_oc": 0, "mem_oc": 100, "fan": 0,
      "speed": 12.3, "power": 0.389
    },
    "Cryptonight-Monero":
    {
      "bin": "/home/m1/NVOC/mining/miners/xmr-stak/xmr-stak_miner --currency monero7 --noCPU --noAMD -o {HOST}:{PORT} -u {NAME}.{MINER} -p x -i 0",
      "power_limit": 100, "gpu_oc": 0, "mem_oc": 0, "fan": 0,
      "speed": 0.000002, "power": 0.325
    },
    "Equihash":
    {
      "bin": "/home/m1/NVOC/mining/miners/ewbf/3_4/miner --eexit 3 --fee 0 --pec --server {HOST} --user {NAME}.{MINER} --pass z --port {PORT}",
      "power_limit": 76, "gpu_oc": 150, "mem_oc": 400, "fan": 0,
      "speed": 0.000001140, "power": 0.397
    },
    "Ethash":
    {
      "bin": "/home/m1/NVOC/mining/miners/ethminer/latest/ethminer -S {HOST}:{PORT} -O {NAME}.{MINER}:x -U",
      "power_limit": 100, "gpu_oc": 0, "mem_oc": 0, "fan": 0,
      "speed": 0.087, "power": 0.397

**Comment by LuKePicci** [comment]
These values matches correctly what you have in 1bash you linked. Are you sure the second round of setting is not due to an occurring switch to some coin for which you have set OC to 0?

**Comment by papampi** [comment]
@snippy62, OC values for mph and nice switch are the lower case settings, make sure you set them correctly, the upper case values are for wtm and no switching.

**Comment by papampi** [comment]
@LuKePicci , we should add a comment in 1bash so users dont get mixed up.
I think we have one at the start of algo oc, but I think it need to have one before lower case values again ...

Isnt it possible to merge them all into uppercase ? so nice and mph read from those too?

**Comment by LuKePicci** [comment]
Wasn't that comment there already?

It is possible, but mph and nicehash use different algo names w.r.t. names used by WTM and nvOC. For example I can put ETHASH_\*\_OVERCLOCK into salfter-like switchers but nicehash is calling it "daggerhashimoto", if users search for daggerhashimoto I think they won't end up in setting the ETHASH_* stuff. Same thing for other algos, I don't remember which one.

**Comment by papampi** [comment]
I think only nicehash uses daggerhashimoto, rest are same.

**Comment by snippy62** [comment]
sorry had to work today so i went through and placed a difrent value on each and found that the daggerhashimoto is what its taking the value from evan though im mining at Mining pool hub so i was able to fix the OC issue ...... and BTW i did see the comet that says uppercase and lowercase but me not knowing nice hash would of never guessed that daggerhashimoto was my etash and your trying to make simple for everyday user :-)

**Comment by papampi** [comment]
Yes, salfter switchers used to have different settings, I think if @LuKePicci could find a way to unify all of them would be great so that users only need to make changes to one set of OC values.

**Comment by LuKePicci** [comment]
WTM-> Ethash
NICEHASH-> daggerhashimoto
MPH-> Ethash

WTM-> Zhash
NICEHASH-> n/a
MPH -> Equihash-BTG

WTM-> CNHeavy
NICEHASH-> CryptonightHeavy
MPH-> n/a ( I bet on "Cryptonight-Heavy" in case it appears in future )

WTM-> CryptoNightV7
NICEHASH-> CryptoNightV7
MPH-> Cryptonight-Monero

WTM-> Lyra2REv2
NICEHASH-> Lyra2REv2
MPH-> Lyra2RE2  ( they have been pure bastards here... )


and so on... how could I do even a bit of magic to unify something?

For sure there should be ethash_CORE_OVERCLOCK and ethash_MEMORY_OVERCLOCK and ethash_POERLIMIT_WATTS linked to MPH'ethash, originally in 2.0 there was daggerhashimoto for all salfter switchers but at the cost of having both it should be clear. I will do my best adding some more info in 1bash to help users avoid confusion but I can't see any viable magic here.

**Comment by papampi** [comment]
Too many ... never thought so ...

**Comment by LuKePicci** [comment]
Can I drop Blake_Vanilla ? I don't see anymore in mph...

**Comment by papampi** [comment]
It looks like mph removed its coin
