### ISSUE TITLE
cpuOPT miner fails to compile  

### ISSUE THREAD

**Issue by snippy62** [papampi/nvOC_by_fullzero#168]
get an error that says "dose not appear to contain cmakelists.txt
specify --help for usage or press the help button on the cmake GUI"
make :*** No rule to make target 'install'.  Stop.
This is when trying to compile after running the upgrade comand and it upgrads the miners the i choose C to compile cpuminer

**Comment by snippy62** [comment]
Checking if bn.h bignum error is fixed for compiling miners or not
bn.h openssl already fixed for compiling miners

Select miners to compile (multiple comma separated values: 1,6,7)
1 - ASccminer
2 - KTccminer
3 - KTccminer-cryptonight
4 - KXccminer
5 - NAccminer
6 - SPccminer
7 - TPccminer
8 - vertminer
9 - ANXccminer
C - cpuminer
R - MSFTccminer (RVN)
U - SUPRminer
X - xmr-stak

Do your Choice: [A]LL [1] [2] [3] [4] [5] [6] [7] [8] [9] [C] [R] [U] [X] [E]xit: C
C
Compiling cpuminer
 This could take a while ...
Submodule path 'src': checked out 'bfd1c002f98f2d63f2174618838afc28cf4ffffe'
mkdir: cannot create directory ‘/home/m1/NVOC/test/miners/cpuOPT/src/build’: File exists
CMake Error: The source directory "/home/m1/NVOC/test/miners/cpuOPT/src" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
make: *** No rule to make target 'install'.  Stop.
Stopping miner
screen killed (pid 27067)
screen killed (pid 27436)
cp: cannotChecking if bn.h bignum error is fixed for compiling miners or not
bn.h openssl already fixed for compiling miners

Select miners to compile (multiple comma separated values: 1,6,7)
1 - ASccminer
2 - KTccminer
3 - KTccminer-cryptonight
4 - KXccminer
5 - NAccminer
6 - SPccminer
7 - TPccminer
8 - vertminer
9 - ANXccminer
C - cpuminer
R - MSFTccminer (RVN)
U - SUPRminer
X - xmr-stak

Do your Choice: [A]LL [1] [2] [3] [4] [5] [6] [7] [8] [9] [C] [R] [U] [X] [E]xit: C
C
Compiling cpuminer
 This could take a while ...
Submodule path 'src': checked out 'bfd1c002f98f2d63f2174618838afc28cf4ffffe'
mkdir: cannot create directory ‘/home/m1/NVOC/test/miners/cpuOPT/src/build’: File exists
CMake Error: The source directory "/home/m1/NVOC/test/miners/cpuOPT/src" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
make: *** No rule to make target 'install'.  Stop.
Stopping miner
screen killed (pid 27067)
screen killed (pid 27436)
cp: cannot stat '/home/m1/NVOC/test/miners/cpuOPT/src/build/cpuminer': No such file or directory

Finished compiling cpuminer
Restarting nvOC...
~/NVOC/test
m1@m1-desktop:~/NVOC/test$ 

 stat '/home/m1/NVOC/test/miners/cpuOPT/src/build/cpuminer': No such file or directory

Finished compiling cpuminer
Restarting nvOC...
~/NVOC/test
m1@m1-desktop:~/NVOC/test$

**Comment by snippy62** [comment]
tail -f /home/m1/NVOC/test/nvoc_logs/cpuminer-screenlog.0
m1@m1-desktop:~$ tail -f /home/m1/NVOC/test/nvoc_logs/cpuminer-screenlog.0
     A CPU miner with multi algo support and optimized for CPUs
     with AES_NI and AVX2 and SHA extensions.
     BTC donation address: 12tdvfF7KmAsihBXQXynT6E6th2c2pByTT

CPU: Intel(R) Core(TM) i3 CPU         550  @ 3.20GHz.
SW built on Jun 26 2018 with GCC 5.4.0.
CPU features: SSE2 SSE4.2.
SW features: SSE2 AES SSE4.2 AVX AVX2.
Algo features: SSE2 AES.
The SW build requires a CPU with AES and AVX2!

when runnung cpu miner the glake window produces

tail -f /home/m1/NVOC/test/nvoc_logs/cpuminer-screenlog.0
m1@m1-desktop:~$ tail -f /home/m1/NVOC/test/nvoc_logs/cpuminer-screenlog.0
     A CPU miner with multi algo support and optimized for CPUs
     with AES_NI and AVX2 and SHA extensions.
     BTC donation address: 12tdvfF7KmAsihBXQXynT6E6th2c2pByTT

CPU: Intel(R) Core(TM) i3 CPU         550  @ 3.20GHz.
SW built on Jun 26 2018 with GCC 5.4.0.
CPU features: SSE2 SSE4.2.
SW features: SSE2 AES SSE4.2 AVX AVX2.
Algo features: SSE2 AES.
The SW build requires a CPU with AES and AVX2!
And stays on that screen but if i go and download the same version from 
https://github.com/JayDDee/cpuminer-opt
Extract cpuminer source.

tar xvzf cpuminer-opt-3.8.1.1.tar.gz
cd cpuminer-opt-3.8.1.1
./autogen.sh
CFLAGS="-O3 -march=native -Wall" ./configure --with-curl
make
than i simply copy the install dir and rename it to the cpuOPT in the miners folder 
than my out put in glake looks good  SCREEN -c /home/m1/NVOC/test/screenrc-cpuminer -dmSL cpuminer /home/m1/NVOC/test/miners/cpuOPT/cpuminer -o stratum+tcp://pool.supportxmr.com:5555 -u 43pAJJobgA7dCpj82yorqJjBdUa3zfgPeav53hkKQwzAPNYniwzcxGeDxFSgCsqRxb3Cx1iR8xWtw6KurEnFS4nU7XFCRdK.Snippy6 -p x -t 4 -a cryptonightv7

         **********  cpuminer-opt 3.8.8.1  *********** 
     A CPU miner with multi algo support and optimized for CPUs
     with AES_NI and AVX2 and SHA extensions.
     BTC donation address: 12tdvfF7KmAsihBXQXynT6E6th2c2pByTT

CPU: Intel(R) Core(TM) i3 CPU         550  @ 3.20GHz.
SW built on Jul 29 2018 with GCC 5.4.0.
CPU features: SSE2 SSE4.2.
SW features: SSE2 SSE4.2.
Algo features: SSE2 AES.
Start mining with SSE2.

[2018-07-29 22:42:59] Starting Stratum on stratum+tcp://pool.supportxmr.com:5555
[2018-07-29 22:42:59] 4 miner threads started, using 'cryptonightv7' algorithm.
[2018-07-29 22:42:59] Stratum difficulty set to 10000
[2018-07-29 22:43:07] CPU #0: 66 H, 8.79 H/s
[2018-07-29 22:43:08] CPU #2: 66 H, 8.29 H/s
[2018-07-29 22:43:08] CPU #1: 66 H, 8.11 H/s
[2018-07-29 22:43:08] CPU #3: 66 H, 7.87 H/s
[2018-07-29 22:43:20] CPU #3: 94 H, 7.80 H/s
[2018-07-29 22:43:20] CPU #2: 112 H, 8.98 H/s
[2018-07-29 22:43:20] CPU #1: 107 H, 8.68 H/s
[2018-07-29 22:43:20] CPU #0: 112 H, 8.63 H/s

**Comment by snippy62** [comment]
i dont know what the issue is when it try to recompile it self but thought i would share since somone else having issue on the discord

**Comment by LuKePicci** [comment]
So, if I understanf correctly the situation, the compiler script is failing to ompile the sources, but if you get those sources somewhere else the compilation is successful. Could you let me know where you downloaded the working sources?

________________________________
Da: snippy62 <notifications@github.com>
Inviato: Monday, July 30, 2018 7:49:35 AM
A: papampi/nvOC_by_fullzero_Community_Release
Cc: Subscribed
Oggetto: Re: [papampi/nvOC_by_fullzero_Community_Release] CPU fails to Compile (#168)


i dont know what the issue is when it try to recompile it self but thought i would share since somone else having issue on the discord

**Comment by snippy62** [comment]
https://github.com/JayDDee/cpuminer-opt

**Comment by LuKePicci** [comment]
Which branch/commit hash exactly?

________________________________
Da: snippy62 <notifications@github.com>
Inviato: Monday, July 30, 2018 4:22:04 PM
A: papampi/nvOC_by_fullzero_Community_Release
Cc: Luca Piccirillo; Assign
Oggetto: Re: [papampi/nvOC_by_fullzero_Community_Release] CPU fails to Compile (#168)


https://github.com/JayDDee/cpuminer-opt

**Comment by snippy62** [comment]
JayDDee v3.8.8.1

**Comment by snippy62** [comment]
https://github.com/JayDDee/cpuminer-opt from this page I download as zip than compile as the release notes say

Extract cpuminer source.
tar xvzf cpuminer-opt-3.8.8.1.tar.gz
cd cpuminer-opt-3.8.8.1
./autogen.sh
CFLAGS="-O3 -march=native -Wall" ./configure --with-curl
make

**Comment by snippy62** [comment]
sorry I had 3.8.1.1 its 3.8.8.1

**Comment by LuKePicci** [comment]
I opened a PR on nvOC miners repo, I can't reference it here because this issue is on a different one.
Apart from the compile issue could you confirm that on latest 19-2.1  branch cpumining settings launch and logging in guake and nvOC cpuminer-log work fine?

**Comment by snippy62** [comment]
for the most part it is. the odd time 1 out of 10 it dose not open a glake tab But I can recall the cpu miner with the screen command from ssh

**Comment by snippy62** [comment]
ill add that when it didn't launch proper was after playing around and I could have closed the tab and left miner going and than restart with the miner going......off of a fresh restart ive never had it fail

**Comment by LuKePicci** [comment]
Fixed, see nvoc_miners repo for related PR.
