### ISSUE TITLE
Can not download at mega.nz

### ISSUE THREAD

**Issue by aliceaia** [papampi/nvOC_by_fullzero#18]
Currently download limit mega.nz, please upload google drive. Thank you

**Comment by cartesien** [comment]
look at this : 
https://bitcointalk.org/index.php?topic=1854250.msg27677087#msg27677087

**Comment by damNmad** [comment]
@aliceaia can you please close this, as the issue has been already resolved. Thanks.

**Comment by papampi** [comment]
More links added
