### ISSUE TITLE
upPASTE: syntax error in if statement

### ISSUE THREAD

**Issue by LuKePicci** [papampi/nvOC_by_fullzero#197]
https://github.com/papampi/nvOC_by_fullzero_Community_Release/blob/997484030a6e49977078c2bcf01907602bc3dd04/upPASTE#L12

This should be instead:
```
if wget … && [[ -f …. ]]
then
 …
```

**Comment by papampi** [comment]
https://github.com/papampi/nvOC_by_fullzero_Community_Release/commit/332beaf069d710aea425c886fd9d7c8180d96154
