### ISSUE TITLE
Coin auto convert to BTC

### ISSUE THREAD

**Issue by papampi** [papampi/nvOC_by_fullzero#200]
What is this COIN_AUTOCONVERT_TO_BTC?
I'm getting an error on nvOC report
`
NVOC/mining/nvOC: line 849: $ETH_AUTOCONVERT_TO_BTC: bad substitution
`

**Comment by LuKePicci** [comment]
I don't know what that option stands for. Regarding the report, that substitution line was changed in #146, it probably gives error when that variable is not set.

**Comment by LuKePicci** [comment]
I can't see any implementation of such feature, I think we can simply drop its reporting snippet as well.

**Comment by papampi** [comment]
Fixed in https://github.com/papampi/nvOC_by_fullzero_Community_Release/pull/203
