### ISSUE TITLE
XMR-Stak don't start on 3main launching

### ISSUE THREAD

**Issue by cartesien** [papampi/nvOC_by_fullzero#221]
> > rig IP: 192.xxx.1.x44
> 
> 
> rig MAC: b8:00:00:00:00:9e  
> 
> 
> 01:00.0 VGA compatible controller: NVIDIA Corporation Device 1b81 (rev a1)
> 02:00.0 VGA compatible controller: NVIDIA Corporation Device 1c03 (rev a1)
> 03:00.0 VGA compatible controller: NVIDIA Corporation Device 1c03 (rev a1)
> 05:00.0 VGA compatible controller: NVIDIA Corporation Device 1b81 (rev a1)
> 06:00.0 VGA compatible controller: NVIDIA Corporation Device 1c03 (rev a1)
> 07:00.0 VGA compatible controller: NVIDIA Corporation Device 1b81 (rev a1)
> 08:00.0 VGA compatible controller: NVIDIA Corporation Device 1b81 (rev a1)
> 09:00.0 VGA compatible controller: NVIDIA Corporation Device 1c03 (rev a1)
> 0a:00.0 VGA compatible controller: NVIDIA Corporation Device 1c03 (rev a1)
> 0b:00.0 VGA compatible controller: NVIDIA Corporation Device 1b81 (rev a1)
> 
> 
> Sun Oct 28 19:30:45 2018       
> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 410.66       Driver Version: 410.66       CUDA Version: 10.0     |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |===============================+======================+======================|
> |   0  GeForce GTX 1070    On   | 00000000:01:00.0  On |                  N/A |
> | 55%   29C    P0    37W / 105W |    128MiB /  8119MiB |     33%      Default |
> +-------------------------------+----------------------+----------------------+
> |   1  GeForce GTX 106...  On   | 00000000:02:00.0 Off |                  N/A |
> | 55%   26C    P8     8W / 105W |      9MiB /  6078MiB |      0%      Default |
> +-------------------------------+----------------------+----------------------+
> |   2  GeForce GTX 106...  On   | 00000000:03:00.0 Off |                  N/A |
> | 55%   26C    P8     8W / 105W |      9MiB /  6078MiB |      0%      Default |
> +-------------------------------+----------------------+----------------------+
> |   3  GeForce GTX 1070    On   | 00000000:05:00.0 Off |                  N/A |
> | 55%   21C    P8     6W / 105W |      9MiB /  8119MiB |      0%      Default |
> +-------------------------------+----------------------+----------------------+
> |   4  GeForce GTX 106...  On   | 00000000:06:00.0 Off |                  N/A |
> | 55%   29C    P8     7W / 100W |      9MiB /  6078MiB |      0%      Default |
> +-------------------------------+----------------------+----------------------+
> |   5  GeForce GTX 1070    On   | 00000000:07:00.0 Off |                  N/A |
> | 55%   24C    P8    10W / 100W |      9MiB /  8119MiB |      0%      Default |
> +-------------------------------+----------------------+----------------------+
> |   6  GeForce GTX 1070    On   | 00000000:08:00.0 Off |                  N/A |
> | 55%   24C    P8     6W / 100W |      9MiB /  8119MiB |      0%      Default |
> +-------------------------------+----------------------+----------------------+
> |   7  GeForce GTX 106...  On   | 00000000:09:00.0 Off |                  N/A |
> | 55%   24C    P8     7W / 110W |      9MiB /  6078MiB |      0%      Default |
> +-------------------------------+----------------------+----------------------+
> |   8  GeForce GTX 106...  On   | 00000000:0A:00.0 Off |                  N/A |
> | 55%   26C    P8     7W / 110W |      9MiB /  6078MiB |      0%      Default |
> +-------------------------------+----------------------+----------------------+
> |   9  GeForce GTX 1070    On   | 00000000:0B:00.0 Off |                  N/A |
> | 55%   22C    P8     6W / 115W |      9MiB /  8119MiB |      0%      Default |
> +-------------------------------+----------------------+----------------------+
>                                                                                
> +-----------------------------------------------------------------------------+
> | Processes:                                                       GPU Memory |
> |  GPU       PID   Type   Process name                             Usage      |
> |=============================================================================|
> |    0      1167      G   /usr/lib/xorg/Xorg                            97MiB |
> |    0      1985      G   compiz                                        28MiB |
> |    1      1167      G   /usr/lib/xorg/Xorg                             6MiB |
> |    2      1167      G   /usr/lib/xorg/Xorg                             6MiB |
> |    3      1167      G   /usr/lib/xorg/Xorg                             6MiB |
> |    4      1167      G   /usr/lib/xorg/Xorg                             6MiB |
> |    5      1167      G   /usr/lib/xorg/Xorg                             6MiB |
> |    6      1167      G   /usr/lib/xorg/Xorg                             6MiB |
> |    7      1167      G   /usr/lib/xorg/Xorg                             6MiB |
> |    8      1167      G   /usr/lib/xorg/Xorg                             6MiB |
> |    9      1167      G   /usr/lib/xorg/Xorg                             6MiB |
> +-----------------------------------------------------------------------------+
> 
> 
> LAUNCHING:  MINER TEMPCONTROL
> 
> process in screen temp, guake terminal Tab (f12), 'nvOC temp-log'
>  2476 pts/19   S+     0:00 tail -n 0 -f /home/m1/NVOC/mining/nvoc_logs/tempcontrol-screenlog.0
> 
> 
> LAUNCHING:  WTM PROFIT CHECK 
> 
> Power limit for GPU 00000000:01:00.0 was set to 105.00 W from 105.00 W.
> All done.
> Power limit for GPU 00000000:02:00.0 was set to 105.00 W from 105.00 W.
> All done.
> Power limit for GPU 00000000:03:00.0 was set to 105.00 W from 105.00 W.
> All done.
> Power limit for GPU 00000000:05:00.0 was set to 105.00 W from 105.00 W.
> All done.
> Power limit for GPU 00000000:06:00.0 was set to 100.00 W from 100.00 W.
> All done.
> Power limit for GPU 00000000:07:00.0 was set to 100.00 W from 100.00 W.
> All done.
> Power limit for GPU 00000000:08:00.0 was set to 100.00 W from 100.00 W.
> All done.
> Power limit for GPU 00000000:09:00.0 was set to 110.00 W from 110.00 W.
> All done.
> Power limit for GPU 00000000:0A:00.0 was set to 110.00 W from 110.00 W.
> All done.
> Power limit for GPU 00000000:0B:00.0 was set to 115.00 W from 115.00 W.
> All done.
> Auto Start Miner Set to YES
> 
> 
> 
> LAUNCHING:  MINER (coin: XMR, algo: CRYPTONIGHTV8)
>     
>   Attribute 'GPUGraphicsClockOffset' (MINER:0[gpu:0]) assigned value 100.
> 
> vm.nr_hugepages = 128
> screen -c /home/m1/NVOC/mining/screenrc-miner -dmSL miner /home/m1/NVOC/mining/miners/XMR_Stak/recommended/xmr-stak --currency cryptonight_v8 --noCPU --noAMD -o pool.supportxmr.com:7777 -u 46sABjRJSTsJviqVAHeQUFUsFvTnmNyfsQVpxYJBxU6Ndq5xdGQEVa84De19FVYeGNhPunknown9ohQ1UbdgUnApakc -p MINER:cryptatometrader44couriel.com -i 3
>     
>     SCREEN -c /home/m1/NVOC/mining/screenrc-miner -dmSL miner /home/m1/NVOC/mining/miners/XMR_Stak/recommended/xmr-stak --currency cryptonight_v8 --noCPU --noAMD -o pool.supportxmr.com:7777 -u 46sABjRJSTsJviqVAHeQUFUsFvTnmNyfsQVpxYJBxU6Ndq5xdGQEVa84De19FVYeGNhPunknown9ohQ1UbdgUnApakc -p MINER:cryptatometrader44couriel.com -i 3
>     
> Miner output: ./nvOC miner-log
>     
>     
>     SCREEN -c /home/m1/NVOC/mining/screenrc-miner -dmSL miner /home/m1/NVOC/mining/miners/XMR_Stak/recommended/xmr-stak --currency cryptonight_v8 --noCPU --noAMD -o pool.supportxmr.com:7777 -u 46sABjRJSTsJviqVAHeQUFUsFvTnmNyfsQVpxYJBxU6Ndq5xdGQEVa84De19FVYeGNhPunknown9ohQ1UbdgUnApakc -p MINER:cryptatometrader44couriel.com -i 3
>   Attribute 'GPUMemoryTransferRateOffset' (MINER:0[gpu:0]) assigned value 1125.
> 
>   Attribute 'GPUGraphicsClockOffset' (MINER:0[gpu:1]) assigned value 100.
> 
>   Attribute 'GPUMemoryTransferRateOffset' (MINER:0[gpu:1]) assigned value 1050.
> 
>   Attribute 'GPUGraphicsClockOffset' (MINER:0[gpu:2]) assigned value 100.
> 
>   Attribute 'GPUMemoryTransferRateOffset' (MINER:0[gpu:2]) assigned value 1050.
> 
>   Attribute 'GPUGraphicsClockOffset' (MINER:0[gpu:3]) assigned value 100.
> 
>   Attribute 'GPUMemoryTransferRateOffset' (MINER:0[gpu:3]) assigned value 1050.
> 
>   Attribute 'GPUGraphicsClockOffset' (MINER:0[gpu:4]) assigned value 100.
> 
>   Attribute 'GPUMemoryTransferRateOffset' (MINER:0[gpu:4]) assigned value 1000.
> 
>   Attribute 'GPUGraphicsClockOffset' (MINER:0[gpu:5]) assigned value 100.
> 
>   Attribute 'GPUMemoryTransferRateOffset' (MINER:0[gpu:5]) assigned value 1050.
> 
>   Attribute 'GPUGraphicsClockOffset' (MINER:0[gpu:6]) assigned value 100.
> 
>   Attribute 'GPUMemoryTransferRateOffset' (MINER:0[gpu:6]) assigned value 1050.
> 
>   Attribute 'GPUGraphicsClockOffset' (MINER:0[gpu:7]) assigned value 100.
> 
>   Attribute 'GPUMemoryTransferRateOffset' (MINER:0[gpu:7]) assigned value 1300.
> 
>   Attribute 'GPUGraphicsClockOffset' (MINER:0[gpu:8]) assigned value 100.
> 
>   Attribute 'GPUMemoryTransferRateOffset' (MINER:0[gpu:8]) assigned value 1300.
> 
>   Attribute 'GPUGraphicsClockOffset' (MINER:0[gpu:9]) assigned value 100.
> 
>   Attribute 'GPUMemoryTransferRateOffset' (MINER:0[gpu:9]) assigned value 1500.
> 
>   Attribute 'GPULogoBrightness' (MINER:0[gpu:0]) assigned value 100.
>   Attribute 'GPULogoBrightness' (MINER:0[gpu:1]) assigned value 100.
>   Attribute 'GPULogoBrightness' (MINER:0[gpu:2]) assigned value 100.
>   Attribute 'GPULogoBrightness' (MINER:0[gpu:3]) assigned value 100.
>   Attribute 'GPULogoBrightness' (MINER:0[gpu:4]) assigned value 100.
>   Attribute 'GPULogoBrightness' (MINER:0[gpu:5]) assigned value 100.
>   Attribute 'GPULogoBrightness' (MINER:0[gpu:6]) assigned value 100.
>   Attribute 'GPULogoBrightness' (MINER:0[gpu:7]) assigned value 100.
>   Attribute 'GPULogoBrightness' (MINER:0[gpu:8]) assigned value 100.
>   Attribute 'GPULogoBrightness' (MINER:0[gpu:9]) assigned value 100.
> 
> Please enter:
> 

As you can see above, i have a interaction demand displayed that ask me to push enter keyboard key.

If i launch command manually, Xmr-stak uses parameters on his files that generated by itself at the first start. 

Another problem seems to be the memory problem. I ca't find the files that are quoted intheir config.txt file.

**Comment by cartesien** [comment]
I think the problem comes from the fact that xmr-stak wants a config.txt file and necessarily .txt pools, whatever -u and -o that is placed behind the executable.

Maybe @psychocrypt's can tell us more about it.

so i kill the screen xxxx.miner process by hand without killing the others and launched xmr-stak 2.5.2 in the directory where the executable can be found from another terminal window

Watchdog and tempcontrol can thus regulate the temperature and the rest even if I launched it by hand.

thank you for your future help

Translated from French with Google translation and not re-read for correction.

**Comment by cartesien** [comment]
I also tried to modify 0miner file in cryptonight section : 

```
>   HCD=${NVOC}/miners/XMR_Stak/"${!xversion}"/xmr-stak
>   echo $LAUNCH $HCD  $UCCALGO --noCPU --noAMD -c  "/home/m1/NVOC/mining/miners/XMR_Stak/2.5.2/xmr-stak/config.txt" -C "/home/m1/NVOC/mining/miners/XMR_Stak/2.5.2/xmr-stak/pools.txt" -o "${!xpool}":"${!xport}" -u "${!xaddr}" -p "$MINER_PWD" -i 3
>   eval $LAUNCH $HCD  $UCCALGO --noCPU --noAMD -c  "/home/m1/NVOC/mining/miners/XMR_Stak/2.5.2/xmr-stak/config.txt" -C "/home/m1/NVOC/mining/miners/XMR_Stak/2.5.2/xmr-stak/pools.txt" -o "${!xpool}":"${!xport}" -u "${!xaddr}" -p "$MINER_PWD" -i 3
```


But i had same results at each launch : 
```
Configuration stored in file '/home/m1/NVOC/mining/miners/XMR_Stak/2.5.2/xmr-stak/config.txt'
Please enter:
```

**Comment by papampi** [comment]
Have you tested running in local mode, press enter in gnome-terminal when asked?
I think it only needs that enter the first time

**Comment by psychocrypt** [comment]
config.txt is always required.

**Comment by cartesien** [comment]
> 
> 
> Have you tested running in local mode, press enter in gnome-terminal when asked?
> I think it only needs that enter the first time

Yes i tried to press enter in terminal but it's not efficient.
i also tried in the screen canal dedicated to miner and press enter but, i seen that it create a config.txt file in /home/m1 directory.

I think it would be better to launch one time manuelly to create all necessary files and just launch the xmr-stak mining binary file compiled.

**Comment by cartesien** [comment]
I did not find the files listed in the help built into the config.txt file.

Then I created them myself and I only put the requested values and then restarted my machine.

> * To set large page support, add the following to "/etc/sysctl.d/60-hugepages.conf":
>  *     vm.nr_hugepages=128

>  * To increase the memlock (ulimit -l), add following lines to /etc/security/limits.d/60-memlock.conf:
>  *     *    - memlock 262144
>  *     root - memlock 262144

Apparently xmr-stak can now use a lot of memory and does not make any more mistakes about launching.

```
Last login: Sun Oct 28 20:12:02 2018 from 
m1@MINER:~$ ulimit -l
262144
m1@MINER:~$ /sbin/sysctl vm.nr_hugepages
vm.nr_hugepages = 128
```


Translated from French with Google translation and not re-read for correction.

**Comment by LuKePicci** [comment]
I have included a dummy config.txt into the last xmr-stak 2.5.2 package, but it is not clear where those files are expected to be placed (home? current dir? miner dir?), there is a command line option to explicitly select the path of those files but it is not clear whether or not their contents get always overridden by command line or not. Would be a much cleaner solution if the config.txt could be dropped completely allowing pure cmdline config. Meanwhile if you manage to dig further into xmr-stak logics to pick its config files let us know, will do what is necessary to let it run unattended.

**Comment by psychocrypt** [comment]
you can have the config.txt everywhere if you set -c PATH/config.txt.
Please check with --help if -c is the correct option I am currently not
100% sure

**Comment by cartesien** [comment]
I also tried with theses 2 options in 0 miner file : 

-c PATH/FILE config.txt
- -C PATH/Pools.txt
`
  echo $LAUNCH $HCD  $UCCALGO --noCPU --noAMD -c  "/home/m1/NVOC/mining/miners/XMR_Stak/2.5.2/xmr-stak/config.txt" -C "/home/m1/NVOC/mining/miners/XMR_Stak/2.5.2/xmr-stak/pools.txt" -o "${!xpool}":"${!xport}" -u "${!xaddr}" -p "$MINER_PWD" -i 3`


```

Mon Oct 29 19:26:54 CET 2018 - Miner is running, 3main killing miner
    SCREEN -c /home/m1/NVOC/mining/screenrc-miner -dmSL miner /home/m1/NVOC/mining/miners/XMR_Stak/recommended/xmr-stak --currency cryptonight_v8 --noCPU --noAMD -c /home/m1/NVOC/mining/miners/XMR_Stak/2.5.2/xmr-stak/config.txt -C /home/m1/NVOC/mining/miners/XMR_Stak/2.5.2/xmr-stak/pools.txt -o pool.supportxmr.com:7777 -u 46sABjRJSTsJviqVAHeQUFUsFvTnmNyfsQVpxYJBxU6Ndq5xdGQEVa84De19FVYeGNhPNaUqkQAFsP79ohQ1UbdgUnApakc -p ATOMICMINER44:cryptatometrader44couriel.com -i 3
Configuration stored in file '/home/m1/NVOC/mining/miners/XMR_Stak/2.5.2/xmr-stak/config.txt'
Please enter:
```
I always have this asked interaction "please enter :"

**Comment by LuKePicci** [comment]
That path sounds wrong to me, it should be /home/m1/NVOC/mining/miners/XMR_Stak/2.5.2/config.txt

**Comment by cartesien** [comment]
Correction : With good PATH in 0miner file, xmr-stak start normally

>   HCD=${NVOC}/miners/XMR_Stak/"${!xversion}"/xmr-stak
>   echo $LAUNCH $HCD  $UCCALGO --noCPU --noAMD -c  "/home/m1/NVOC/mining/miners/XMR_Stak/2.5.2/config.txt" -C "/home/m1/NVOC/mining/miners/XMR_Stak/2.5.2/pools.txt" -o "${!xpool}":"${!xport}" -u "${!xaddr}" -p "$MINER_PWD" -i 0
>   eval $LAUNCH $HCD  $UCCALGO --noCPU --noAMD -c  "/home/m1/NVOC/mining/miners/XMR_Stak/2.5.2/config.txt" -C "/home/m1/NVOC/mining/miners/XMR_Stak/2.5.2/pools.txt" -o "${!xpool}":"${!xport}" -u "${!xaddr}" -p "$MINER_PWD" -i 0

Note for others users, not for lukepicci : -i option is to define httpd deamon port like 8080 or 10000 or whatever...

**Comment by LuKePicci** [comment]
Correct, and setting the .i option to 0 disables the http api daemon completely.
