### ISSUE TITLE
NICE_CNV8 & NICE_CNHEAVY not displayed by WTM_SWITCHER

### ISSUE THREAD

**Issue by cartesien** [papampi/nvOC_by_fullzero#222]
I tried to use wtm_check with theses params : 
`WTM_AUTO_SWITCH_COINS="ETH;ETC;NICE_ETHASH;XMR;NICE_CNV8;NICE_CNHEAVY;NICE_X16R"`

but WTM_PROFIT_CHECK guake tab don't display all  : 

> Getting BTC price from coindesk.com
> BTC PRICE: 6420.0075 USD
>  
> Current Revenue:
> NICE_X16R 5.83 USD
> XMR 3.79 USD
> ETC 4.39 USD
> NICE_ETHASH 4.36 USD
> ETH 4.36 USD
>  
> Current Profit:
> NICE_X16R: 134 %
> XMR: 87 %
> ETC: 101 %
> NICE_ETHASH: 100 %
> ETH: 100 %
>  
> 
> Check again in 180 seconds

I think new algos for nicehash on WTM website hadn't been added in 1bash, and 0miner file. Would it be posssible to add them for WTM_Switching on Nicehash

**Comment by LuKePicci** [comment]
That list is not related in any way to setup (1bash) or miner selection (0miner), so there is nothing in there that could prevent those algos showing. Check your WTM api url.

**Comment by LuKePicci** [comment]
NICE_CRYPTONIGHTV8 / HEAVY should appear in WTM_SWITCHER output without any modifications to 1bash. Then you also have to define NICE_CRYPTONIGHTV8 / HEAVY coins in 1bash such that they are mapped to the right algo and miner.

**Comment by cartesien** [comment]
> 
> 
> NICE_CRYPTONIGHTV8 / HEAVY should appear in WTM_SWITCHER output without any modifications to 1bash. Then you also have to define NICE_CRYPTONIGHTV8 / HEAVY coins in 1bash such that they are mapped to the right algo and miner.


I added this in 1bash
```
[#NICE_CRYPTONIGHTV7
NICE_CRYPTONIGHT_POOL="cryptonightv7.eu.nicehash.com"
NICE_CRYPTONIGHT_PORT="3363"
NICE_CRYPTONIGHT_WORKER="$WORKERNAME"
NICE_CRYPTONIGHT_EXTENSION_ARGUMENTS=""

#NICE_CRYPTONIGHTV8
NICE_CRYPTONIGHT_POOL="cryptonightv8.eu.nicehash.com"
NICE_CRYPTONIGHT_PORT="3367"
NICE_CRYPTONIGHT_WORKER="$WORKERNAME"
NICE_CRYPTONIGHT_EXTENSION_ARGUMENTS=""]
```

**Comment by LuKePicci** [comment]
Not correct, the suffix after NICE_ has to match the name of the con as returned by WTM_SWITCH, so you have to call them NICE_CRYPTONIGHTV8_* otherwise those settings are picked up only for the old original version of that pow algo.  As I can see here your second block is completely overriding the fisrt one.

**Comment by LuKePicci** [comment]
I will now close this issue because it is related to a configuration mistake rather than a bug. You can discuss this further here in this page if you need.

**Comment by cartesien** [comment]
OK.

Corrected 

> #NICE_CRYPTONIGHTV7
> NICE_CNV7_POOL="cryptonightv7.eu.nicehash.com"
> NICE_CNV7_PORT="3363"
> NICE_CNV7_WORKER="$WORKERNAME"
> NICE_CNV7_EXTENSION_ARGUMENTS=""
> 
> #NICE_CRYPTONIGHTV8
> NICE_CNV8_POOL="cryptonightv8.eu.nicehash.com"
> NICE_CNV8_PORT="3367"
> NICE_CNV8_WORKER="$WORKERNAME"
> NICE_CNV8_EXTENSION_ARGUMENTS=""

**Comment by cartesien** [comment]
> 
> 
> I will now close this issue because it is related to a configuration mistake rather than a bug. You can discuss this further here in this page if you need.

I think if it's up to the users to do the same 1bash after having slightly understood and read the code, then remove the title "esay to use" from the community version of nvOC.

I can understand your annoyance at my difficulties in composing and arranging the code according to my needs, but I doubt to be the only one in this case. The recent messages on BTCTALK seem to indicate that others seem to be in my situation.

When I comment on the default root files, papampi tells me to open an issue for the bug, and when I open an issue for a bug, you close it and tell me that I can keep commenting because it's is a configuration problem and not a bug.

Do you close the project slowly but surely?

Translated from French with Google translation and not re-read for correction.

**Comment by LuKePicci** [comment]
Do not misunderstand me mate, I'm closing this only because it is not something we could "fix", open issues represent a reminder for something to be worked on. Discussion is not locked and I will be happy to help you get all things working if possible. I do this just for being of help to other people, nobody is paying me to do so.

**Comment by cartesien** [comment]
I always have several difficuties with implementation of nicehash with WTM_SWITCHER. I don't know why but i think it's because replacing dash by underscaore.

My modifications don't take effect.
But i'm sure that my URL is the good URL and CNHEAVY was really in 1bash orginal and also in my WTM_AUTO_SWITCH_COINS before but don't shown by WTM switcher

I'm confusing with using NICE_CNV8 or NICE_CRYPTONIGHTV8 (same for CNV7). ANd i don't undertsand wahre i must modify script files, 1bash only ? 0miner file ? What other file ?

Actually, i mine XMR in CNV8 only, but because GPU mining ETH seems to decrease in interrest since ETH ASICs appaered, and CRYPTONIGHT coin increase in interrest beacause of ASIC Résistance militantism, lots of coins could be interresting to mine on WTM Switching including the nicehash pools listed by WTM.

So i think, i will return in WTM SWITCHING but only for ASIC résistants ALGOs because i can't use a noisy ASIC at home instead of GPUs much less noisy. I see that all ASICS become very quickly non-pfofitables after their buyers received and connects them. probably until the next bull run...but noone knows when that bull run will come back.

So please help me to write a good guide to add ourselves all nicehash or MPH pools or each coin can exist in this cryptoworld. Several month i proposed to use a csv file that can be imported with a script into 1bash file. Do you think it's possible to make such a script like that ?

Wrote without google translate and not re-read so excuse me if my english is not always comprehensive.

**Comment by LuKePicci** [comment]
Unless there is some bug somewhere the only file you need to modify to add new nicehash coins is 1bash. This will be true in general for any new coin/algo/miner when we manage to get all oir mienrs converted to a more flexible package format which does not require users to understand or modify code in scripts like 0miner.
