### ISSUE TITLE
Algo and hashrate missing in minerinfo

### ISSUE THREAD

**Issue by papampi** [papampi/nvOC_by_fullzero#240]
Default webinfo not showing algo and average hashrate on 3.1-dev

Any ideas?

```
Currently Mining Coin: ZEL 
Currently Mining ALGO: 
Average Hash Rate: Not yet available for current miner 
```

**Comment by LuKePicci** [comment]
There is still the old `source 0algo_id` in minerinfo, change with
`source ${NVOC}/helpers/coin_algo_mapping`

The `hash_average` is miner-specific does this issue affects them all? Try printing separately `total_hash` and `hash_count` and see what's wrong.

**Comment by papampi** [comment]
Thanks mate, was totally forgotten the coin_algo_mapping.

Commands work fine if remove the escapes we added for json, but not with them.
Tried many miners, none showing hash average.

**Comment by LuKePicci** [comment]
It is probably a problem with quoting, check how I escaped commands for ethminer and z_ewbf which were working in my tests.

**Comment by LuKePicci** [comment]
Nope, just checked, seems like MINER_PATH is not defined anymore. Probably its definition got removed in some merging operation.
