### ISSUE TITLE
Invalid default PHI2 miner

### ISSUE THREAD

**Issue by LuKePicci** [papampi/nvOC_by_fullzero#242]
https://github.com/papampi/nvOC_by_fullzero_Community_Release/blob/1362e73b68ef9fe73fb6dd08ff8843f08203d3a2/1bash.template#L610

It has been proposed to use CryptoDredge instead. Please, check if a simple switch works fine or some other arguments should be added by default to make it mine correctly.

**Comment by papampi** [comment]
Changed in both 3.0 stable and 3.1 dev
https://github.com/papampi/nvOC_by_fullzero_Community_Release/commit/0ecc7220bb487c80da1224d878129d319a181ef6
https://github.com/papampi/nvOC_by_fullzero_Community_Release/commit/00ec49a3540b85fa12fb06d3db6556ec85305a5f
