### ISSUE TITLE
Can't add grin using gminer

### ISSUE THREAD

**Issue by psynauty** [papampi/nvOC_by_fullzero#245]
I want to use the latest gminer (1.23 onwards) to mine grin on sparkpool.
I have attemptedto edit 1bash and attempted to add edits on 0miner but I can't get it to work.
Could you please update the necessary files (1bash, 0miner etc) to enable grin mining?
Beam should be also easy to add for gminer as well.
Thank you

**Comment by papampi** [comment]
Gminer update to 1.25: https://github.com/papampi/nvOC_miners/commit/d6d0ae4667ac3940309456cc031268ae1f284d14
1bash updated, cuckaroo29 and cuckoo Algos added: https://github.com/papampi/nvOC_by_fullzero_Community_Release/commit/bd0874ae85764b686f08a8bbd74ae592e18f6abc
0miner updated, cuckaroo29 and cuckoo Algos added: https://github.com/papampi/nvOC_by_fullzero_Community_Release/commit/8caed3727487a1afe2244168b06b9f24dbb46bca

Please update, test and let us know.

**Comment by psynauty** [comment]
Thanks a million papampi! You're a star!
It's working just fine. 
Mining grin on 8 gpus stable.
9 GPUs test in progress (used to crash on Win10 with 9 and more)
Will keep adding GPUs and update

**Comment by papampi** [comment]
@psynauty Remember not to change GPU pci slots, 
May get into xorg problem.
If that happened restore xorg with:
`bash ~/NVOC/mining/nvOC restore-xorg`

**Comment by psynauty** [comment]
@papampi 9 GPUs flash reboot the system. It's either a B250 mono + cuckaroo29 issue or just miners not currently being geared for more than 8 GPUs (I have 1080 Ti s)

**Comment by papampi** [comment]
Try mining other cons, if it reboots it's a motherboard problem if not it's gminer.
Post issue in gminer forum thread.

**Comment by psynauty** [comment]
same issue with Bminer as well so not an issue with the miner sw.
Could be a mobo constraint.
Where is the gminer thread you are referring to?
Could you point me to it?

**Comment by papampi** [comment]
This is gminer thread in bttalk
https://bitcointalk.org/index.php?topic=5034735.0

But if rig reboots with other miners then for sure it's not miner or os problem, as it happens on both windows and Linux.
Check motherboard bios settings. Or post in alternate mining forum see if anyone can help.
