### ISSUE TITLE
Could you please add support for nicehash  grin and beam using gminer 1.29?

### ISSUE THREAD

**Issue by psynauty** [papampi/nvOC_by_fullzero#246]
If possible to profit switch between them that would also be great.

**Comment by psynauty** [comment]
Happy to report 12x 1080 ti on nicehash cuckaroo29 using gminer 1.31 is super stable.
Go team!

**Comment by LuKePicci** [comment]
mining is stable for me too but tempcontrol (on 3.0-stable) is completely locked out from setting updated fan speeds. I will try the updated one on the 3.1-dev to see if it behaves better.

**Comment by psynauty** [comment]
Temp control works fine for me. 
I tried pushing it to 55 target and decided to leave it to 65. The noise and fan wear not worth it.

**Comment by papampi** [comment]
It feels like nvidia-settings keep changing fan speed and then tempcontrol change it again, it's an endless loop.

**Comment by papampi** [comment]
If I set minimum fan speed higher than what nvidia-settings like, it keeps lowering it and tempcontrol raise it 
If I set it too low, like 30, then nvidia-settings keep raising it and tempcontrol lower it.

**Comment by psynauty** [comment]
That’s odd. 
It seems that nvidia overrides your manual settings then. 
Is there a way to disable that?
In Windows I used to use nvidia inspector to pass smi commands via cmd line to control all settings in a single command per gpu.

**Comment by LuKePicci** [comment]
In my case tempcontrol simply stuck suddenly after some loops, autotemp be nvidia driver is correctly disabled since I can see fan speeds locked to the last change done by tempcontrol.

By the way the problem seems quite simple: gpus are too busy to handle the fan setting change. Sometimes you get an error from nvisia-settings saying it failed to apply fan speed/autotemp toggle. In this last case you will see temps applied by tempcontorl being overridden by autotemp, which is expected. I see gminer is reporting back a lot of info about power, temp and other stuff, maybe it is saturating nvidia driver by such kind of requests already?

**Comment by psynauty** [comment]
I agree but sometimes it felt that it's not a per gpu problem but a CPU / driver saturation bottleneck to handle multiple calls at multiple gpus in short succession. 
What I used to do is put a 1-3 sec delay between applying  settings to each gpu to the reduce the overload. 
Not sure if my assumption is correct or its a per gpu problem as you say or a bit of both. 
And indeed most miners hammer the control plane of the cards

**Comment by LuKePicci** [comment]
I think It's a fake cpu bottlenack, the nvidia-settings is just bad written, seems like it is looping and wasting cpu time while waiting for gpu responses to collect.

**Comment by LuKePicci** [comment]
I've just set GMINER_OPTS to "-w 0 --pec 0", let me see if it works fine now.

**Comment by psynauty** [comment]
You read my mind. I was looking at the gminer options to turn off the overkill reporting. Unless I misunderstood what you are trying to test

**Comment by LuKePicci** [comment]
Definitely better, before it was stopping after a couple of minutes, now it is running for more than an hour, and tempcontrol is still working.

**Comment by psynauty** [comment]
Ace!
Btw, what's your power overhead?
I want to see how I can minimise it if possible. 
It's around 240w (just over 10% of the power the gpus burn). 
I will try and undeclock the CPU for starters  
It's an i7-7700k

**Comment by LuKePicci** [comment]
my 11x1070 rig is mining at 44.0 G/s, each power limited at 100W
```
GPU 0, Target temp: 65, Current: 62, Diff: -3, Fan: 60, Power: 102.79
GPU 1, Target temp: 65, Current: 62, Diff: -3, Fan: 60, Power: 103.85
GPU 2, Target temp: 65, Current: 64, Diff: -1, Fan: 45, Power: 98.71
GPU 3, Target temp: 65, Current: 58, Diff: -7, Fan: 40, Power: 96.54
GPU 4, Target temp: 65, Current: 60, Diff: -5, Fan: 40, Power: 90.64
GPU 5, Target temp: 65, Current: 63, Diff: -2, Fan: 60, Power: 104.75
GPU 6, Target temp: 65, Current: 62, Diff: -3, Fan: 40, Power: 95.12
GPU 7, Target temp: 65, Current: 63, Diff: -2, Fan: 55, Power: 94.99
GPU 8, Target temp: 65, Current: 64, Diff: -1, Fan: 50, Power: 106.31
GPU 9, Target temp: 65, Current: 62, Diff: -3, Fan: 55, Power: 98.99
GPU 10, Target temp: 65, Current: 65, Diff: 0, Fan: 45, Power: 98.84
Sun Feb 17 16:27:16 CET 2019 - All good, will check again in 24.5 seconds
```

Each gpu has a base OC of core +160, mem +500 I still have to tune this, probably will lower mem if hashrate stay there (was 1200 for ethash). Individual small negative offsets on mem OC are also set for a couple of less stable cards.

It is a dual RM850x PSU setup suited for 6GPU+CPU+10pwm fans/7GPU which is actually running 6+CPU+10 fans/5, so not yet at the peak of its efficiency curve.

Rated power at wall socket was 670W for the main PSU only without fans on ethash @ 30MH/s each, it is now 1225W in total for both PSUs including fans on cuckaroo29 @ 4 G/s each.

**Comment by hartmanm** [comment]
I recommend using at least a 106 watt power limit with 1070s.  Using any less with restrict the cores. Some mining clients will only perform optimally with a 115 watt power limit or greater

**Comment by LuKePicci** [comment]
Will check what you say on the second half of the rig, and see if something changes for cuckaroo29. I usually notice such a restriction on ethash/zhash taking place only when temps are above 68 °C and fans spin faster, but it is hitting the hashrate target with no problems at 100W when temps are in the lower 60's range.

**Comment by psynauty** [comment]
4G/s is the top end for 1070s. 
I have two in my HTPC / Gaming rig with SLI enabled and it doesn't interfere with the mining of grin. Using Afterburner at 50% tdp Power, 100C and 300M. 
No need for more. Power hovers around 100-110w. 
But, with the OH power around 100w it's slightly unprofitable as a whole system.

**Comment by LuKePicci** [comment]
+100C/+300M in nvOC or afterburner? In the latter case it would be a +200C/+600M on nvOC, which is not too far from my current +160C/+500M

**Comment by psynauty** [comment]
on afterburner.
I thought that only the mem needs to be doubled on nvOC not the core.
So Core should be the same in nvOC.

**Comment by LuKePicci** [comment]
I never had the chance of playing with oc in windows, so I will trust whatever you tell me about this, I always considered core clocks to be doubled as well but I never tested myself.
