### ISSUE TITLE
Please add support for cuckaroo31 using gminer 1.31 to mine grin31

### ISSUE THREAD

**Issue by psynauty** [papampi/nvOC_by_fullzero#248]
Could you please add grin31 to the coins/algos.
Gminer just released support for it in v1.31.
Thank you

**Comment by papampi** [comment]
Please update, test and let us know.

**Comment by psynauty** [comment]
Hi mate. 
The algo is cuckatoo31 with a t not an r. 
Not sure if it matters. 
Coins could be grin29 and grin31. 
If you could also add the nicehash version that would be great

**Comment by papampi** [comment]
Fixed Cuckatoo31 typo
Added NiceHash Cuckatoo31 and Cuckaroo29 support in 1bash
Whattomine use Grin for Grin29 so we should use the same for whattomine switcher support.

**Comment by psynauty** [comment]
- GRIN on sparkpool works fine. Need to change wallet format to / from .
- GRIN31 on sparkpool reboots the system. Will check if it's related to no of GPUs
- NICE_CUCKAxxx doesn't pass the NICE_ADDRESS but ".Workername" instead. I believe 0miner is missing the below lines:
-- NICE_CUCKAROO29_ADDRESS=$NICE_ADDRESS
-- NICE_CUCKATOO31_ADDRESS=$NICE_ADDRESS
- erroneous semicolon on 1bash at the end of cuckatoo31 stratum (#NICE_CUCKATOO31
NICE_CUCKATOO31_POOL="grincuckatoo31.eu.nicehash.com:")

**Comment by papampi** [comment]
Thanks a lot for the tests.
Fixed Nice in 0miner
Fixed * NICE_CUCKATOO31_POOL in 1bash
Made a change in 0miner and separate Cuckaroo and Cuckatoo algos, may fix Grin31 problem.

**Comment by psynauty** [comment]
all good except grin31 crashes.
I believe it's gminer. They just introduced cuckatoo31 so I believe it will take a few iterations to settle
Thank you!

**Comment by papampi** [comment]
Does miner start and then crash?
You should see miner start command in gnome-terminal.

**Comment by psynauty** [comment]
Miner shows GPU count then system reboots immediately.
Works fine on cuckaroo29.
I tried with 1 GPU and it was fine.

**Comment by papampi** [comment]
Thanks for confirmation.

**Comment by LuKePicci** [comment]
> Whattomine use Grin for Grin29 so we should use the same for whattomine switcher support.

Has wtm listed grin already? I was checking since some weeks ago but grin doesn't show up

**Comment by papampi** [comment]
Yes it's been added for sometimes.
Check if you have all the exchanges enabled.
