### ISSUE TITLE
Could you please add bminer 14.3.1 support for cuckaroo29 and cuckatoo31 (pool and NH)

### ISSUE THREAD

**Issue by psynauty** [papampi/nvOC_by_fullzero#249]
Trying to see if bminer is stable with 12 GPUs on cuckatoo31.
Thanks!

**Comment by papampi** [comment]
I couldnt mine cuckatoo31 on my test rig with gminer either, it gives memory error on gpu1 and gpu2.
Bminer updated.

**Comment by papampi** [comment]
With bminer you should use "%2F" for wallet_address_format instead of "/" in grinmint pool

**Comment by papampi** [comment]
bminer is giving the same insufficient memory on device too, it says only 7800 Mb available, so 8Gb GPU is not enough for cuckatoo31?

Edit:
Looks like cuckatoo31 needs at least 11 Gb card

**Comment by psynauty** [comment]
I'll try with the 1080 ti s
Cuckatoo31 is destined for high memory gpus in the short term and ASICs in
the future so quite heavy on a gpu it seems from a processing / memory
perspective.

**Comment by psynauty** [comment]
Easiest pool vs. pool fee balance is sparkpool. 
I recommend it as the default pool on 1bash. 
Daily payouts

**Comment by psynauty** [comment]
On Nicehash, cuckaroo29 doesn't pass the right uri argument to bminer
Log:
SCREEN -c /home/m1/NVOC/mining/screenrc-miner -dmSL miner /home/m1/NVOC/mining/miners/BMINER/14.3.1/bminer -uri stratum+tcp://NICE_ADDRESS.worker:x@grincuckaroo29.eu.nicehash.com:3371
invalid value "stratum+tcp://NICE_ADDRESS.worker:x@grincuckaroo29.eu.nicehash.com:3371" for flag -uri: Unsupported scheme
Bminer: When Crypto-mining Made Fast (v14.3.1-8d9471b)

**Comment by papampi** [comment]
Add this to 1bash and test

`NICE_CUCKAROO29_POOL_PROTOCOL="cuckaroo29"
`

By default if any coin has no pool protocol 0miner uses default stratum+tcp

**Comment by psynauty** [comment]
on sparkpool it say invalid port.
SCREEN -c /home/m1/NVOC/mining/screenrc-miner -dmSL miner /home/m1/NVOC/mining/miners/BMINER/14.3.1/bminer -uri stratum+tcp://xxx@xxx.com/worker:x@grin.sparkpool.com:6666
invalid value "stratum+tcp://xxx@xxx.com/worker:x@grin.sparkpool.com:6666" for flag -uri: Invalid port in the URI
Bminer: When Crypto-mining Made Fast (v14.3.1-8d9471b)

**Comment by papampi** [comment]
Posted earlier you need to use "%2F" instead of "/" with bminer for wallet address format

**Comment by psynauty** [comment]
True that! I forgot bminer is flakey with the / argument. I believe it needs %40 for the @ 
I get a crash with bminer on 12 GPUs on cuckaroo29. Sigh.........

**Comment by psynauty** [comment]
I'm giving up on bminer for now. Ran out of time.
How can I invoke the miner direct from a cmd line to test things quickly?

**Comment by papampi** [comment]
gnome-terminal posts miner command when it starts.
You can copy the codes after `... -dmSL miner ... `

**Comment by psynauty** [comment]
a quick update on cuckatoo31.
Managed to get 8 gpus running for a short period. Didn't leave it for too long.
With 9 or 10 it is getting freaky and get a lock and reboot.
Weird thing is that after the crash the mobo shows a fault in one of the GPUs (which by slightly jiggling the connector it goes back to ok). Never happens with cuckaroo29.
So cuckatoo31 works on 1.31 but with stability issues past 9 GPUs.
Will stick to cuckaroo29 for now.
You can close the issue.
