### ISSUE TITLE
Aeternity option in gminer should be aeterity not cuckoo. Also please add f2pool as default AE pool

### ISSUE THREAD

**Issue by psynauty** [papampi/nvOC_by_fullzero#257]
I also get error from pool for user name.
I use ak_AEwalletaddressonexchange

**Comment by psynauty** [comment]
I also get an error from the f2pool with user being AE_walletaddressxxx.worker.

**Comment by papampi** [comment]
Fixed GMiner UCCALGO variable in 3.0-stable https://github.com/papampi/nvOC_by_fullzero_Community_Release/commit/4353a91c7907d88f45758131bf39d8ba4176e925
You should edit 1bash and use COIN_EXTENSION_ARGUMENTS in 3.0-stable or COIN_OPTS in 3.1-dev
Grin example 3.0-stable:
`GRIN_EXTENSION_ARGUMENTS="--algo cuckaroo29"
`
Grin example 3.1-dev:
`GRIN_OPTS="--algo cuckaroo29"`

Aeternity algo is CuckooCycle, each miner use its own variable, set it in 1bash based on your miner.

Check with your miner and pool for the error.
