### ISSUE TITLE
Add support for NBminer 21.0 for grin etc algos

### ISSUE THREAD

**Issue by psynauty** [papampi/nvOC_by_fullzero#274]

**Comment by papampi** [comment]
Already added to 3.1-dev and beta_testing
https://github.com/papampi/nvOC_miners/tree/3.1-miners

**Comment by psynauty** [comment]
How do I upgrade to the beta release?

**Comment by papampi** [comment]
https://github.com/papampi/nvOC_by_fullzero_Community_Release/wiki/nvOC-setup-from-a-git-clone
