### ISSUE TITLE
NICE_* address argument missing in miner command line

### ISSUE THREAD

**Issue by psynauty** [papampi/nvOC_by_fullzero#275]
CREEN -c /home/m1/NVOC/mining/screenrc-miner -dmSL miner /home/m1/NVOC/mining/miners/ZENEMYminer/recommended/ccminer -a x16r -o stratum+tcp://x16r.eu.nicehash.com:3366 -u .RIGnvOC -p x -i 19

**Comment by LuKePicci** [comment]
I'm quite confident you have some problems in the *_ADDRESS setting from 1bash

**Comment by psynauty** [comment]
Had to add NICE_X16R_ADDRESS="$NICE ADDRESS"  under NICE X16R in 1bash.

**Comment by LuKePicci** [comment]
Please note this is present already in current template, but whatever coin you add you need to define NICE_*_ADDRESS as well taking 1bash.template contents as example.

**Comment by psynauty** [comment]
Thanks buddy!
