### ISSUE TITLE
Use ubuntu-2d session

### ISSUE THREAD

**Issue by cbesot** [papampi/nvOC_by_fullzero#40]
Hi, I think Unity - 3D is totally useless for mining.
I think you just have to change one line:
In  **/home/m1/.dmrc**
`Session=ubuntu-2d`

**Comment by papampi** [comment]
Tried this, but no visible changes ...

**Comment by LuKePicci** [comment]
Check if this saves some MBytes of vram on the primary gpu, this may be worth for low-memory cards.
