### ISSUE TITLE
webinfo problem

### ISSUE THREAD

**Issue by papampi** [papampi/nvOC_by_fullzero#43]
If I open web page from local machine, clearinfo and minerinfo are not clickable, anyone else has the issue ?
They both work fine from remote.

**Comment by LuKePicci** [comment]
I'll check asap

**Comment by LuKePicci** [comment]
I confirm, it's quite strange TBH. maybe a browser compatibility issue. I tried also with w3m and it works fine.

**Comment by papampi** [comment]
Yup, its nvOC installed firefox issue, can not click on other rigs webinfo from it too.
