### ISSUE TITLE
NVOC path variable not set when upPASTE is used

### ISSUE THREAD

**Issue by Draco-Falcon** [papampi/nvOC_by_fullzero#46]
I tried the new 1.9.2.1 script and end up in a endless loop as the NVOC variable did not get set.

I started with nvOC-V0019-2.0-10GB_Auto_Expand.img

Then I ran this:
#!/bin/bash
echo "Making directory /home/m1/miners..."
mkdir /home/m1/miners
mkdir /home/m1/miners/ewbf
mkdir /home/m1/miners/dstm
cd /home/m1/miners
echo "Copying miners..."
cp -r /home/m1/zec/v3_3 ewbf
cp -r /home/m1/zec/v3_4 ewbf
cp -r /home/m1/zec/zm dstm
cp -r /home/m1/eth/ .
cp -r /home/m1/TPccminer .
cp -r /home/m1/MSFTccminer .
cp -r /home/m1/KTccminer .
cp -r /home/m1/vertminer .
cp -r /home/m1/NAccminer .
cp -r /home/m1/KTccminer-cryptonight .
cp -r /home/m1/ANXccminer .
cp -r /home/m1/SPccminer .
cp -r /home/m1/xmr .
cp -r /home/m1/ASccminer .
cp -r /home/m1/KXccminer .
cp -r /home/m1/KXccminer-skunk .
cp -r /home/m1/pasc .
cp -r /home/m1/cpuOPT .

rm -r /home/m1/zec
rm -r /home/m1/eth
rm -r /hone/m1/TPccminer
rm -r /home/m1/MSFTccminer .
rm -r /home/m1/KTccminer .
rm -r /home/m1/vertminer .
rm -r /home/m1/NAccminer .
rm -r /home/m1/KTccminer-cryptonight .
rm -r /home/m1/ANXccminer .
rm -r /home/m1/SPccminer .
rm -r /home/m1/xmr .
rm -r /home/m1/ASccminer .
rm -r /home/m1/KXccminer .
rm -r /home/m1/KXccminer-skunk .
rm -r /home/m1/pasc .
rm -r /home/m1/cpuOPT .

Next I download the ZIP of the 1.9.2.1 and unzipped the contents into my /home/m1 directory
Then I rebooted

It did not work.

I then added this line to my /etc/environment
NVOC="/home/m1"

Then rebooted again and now it works.

Jim (Falcon)

**Comment by LuKePicci** [comment]
Interesting, have you replaced also 2unix file with the `export NVOC=...` line at the beginning?

Check that you have exactly `bash /home/m1/2unix` as alternative shell command in gnome-terminal "mining" profile setting.

Also try echoing the output from command in 2unix at line 3 from an arbitrary bash script. I need to understand exactly which script does not see NVOC variable exported.

Are you running in LOCAL or REMOTE mode?

**Comment by Draco-Falcon** [comment]
Yes...the beginning of my 2unix has this:
#!/bin/bash

export NVOC="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

firstBOOT="NO"

if grep -q "convert" ${NVOC}/firstBOOT;


Where do I find that alternative shell command in gnome-terminal?  Directory? File?

I am running LOCAL

Jim

**Comment by Draco-Falcon** [comment]
I found the mining profile in the GUI (couldn't find it using SSH).

Anyway, it has this:

bash '/home/m1/2unix'

The only difference I see is that mine has the ' mark

That is the default and I didn't change that.

Jim

**Comment by Draco-Falcon** [comment]
The 3main was executing over and over with not found errors

**Comment by LuKePicci** [comment]
Probably an issue with the LOCAL mode, I'll take a look

**Comment by LuKePicci** [comment]
Ok, I just realized 5watchdog and 6tempcontrol runs in guake instead of screen when in LOCAL mode, and for that reason, as like as 7telegram and 8wtm_* scripts, in that case thay do not inherit NVOC export from 2unix. Please could you confirm adding that `export NVOC=...` line to those two scripts and removing that variable from /etc/environment fix this issue?

edit: wrong, as said below, guake only runs a `tail` command on screen logs for 5watchdog and 6tempcontrol

**Comment by Draco-Falcon** [comment]
I adjusted those two files and then removed the environment variable.  Now I get "bash  /3main: no such file or directory"  in the terminal window

**Comment by LuKePicci** [comment]
I cannot see any correlation between 5watchdog/6tempcontrol and 2unix. Please replace 2unix with this debug script and see what happens

#!/bin/bash
echo "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

**Comment by Draco-Falcon** [comment]
I added the export NVOC= ... to the upPASTE (which I am using cause I am the author of the webui) and now it is working.

**Comment by Draco-Falcon** [comment]
Wouldn't the environment variable I had set be easier than having these export lines all over the place?

**Comment by Draco-Falcon** [comment]
The upPASTE also runs in a guake window

**Comment by LuKePicci** [comment]
There should be a single export in 2unix in my original intention. The problem is guake, that is not inheriting 2unix initial environment. I see salfter switcher runs in screen and open a guake tab attached to it, this would fix the problem avoiding to repeat that export line everywhere.

**Comment by Draco-Falcon** [comment]
How about this:  In the 2unix, if it is a firstBoot, then echo your export into the /etc/environment

like:

sudo echo NVOC="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" >> /etc/environment

I haven't tested that, but something along those lines

**Comment by LuKePicci** [comment]
Would work fine only in nvOC images

**Comment by Draco-Falcon** [comment]
this is nvOC - what else are we doing this for?

**Comment by LuKePicci** [comment]
and way more important, it breaks side-by-side nvOC installs since you are not managing ovewriting of previously existing entries int the /etc(environment

**Comment by Draco-Falcon** [comment]
I don't understand...you are installing a 2nd nvOC on the same hard disk in another location on the same rig?  Why would you want that?

**Comment by LuKePicci** [comment]
Improved testing, development and upgrading experience. You could clone this into /home/m1/nvOC21 (for example) and you try running this new revision, if any problem just revert the original 2unix path in the gnome-termianl profile and nothing gets broken. Also keeping both current/stable and development nvOC tree on the sa rig allow testing different branches on the fly. I still have nvOC 2.0 setup on my rig, and I'm testing nvOC 2.1 on that same rig, if any trouble in the master branch I restore 2.0 in a matter of seconds and I'm done.

**Comment by Draco-Falcon** [comment]
Understood.  As indicated....adding the export NVOC=... to the 3 files (upPASTE, 5watchdog and 6tempcontrol) fixed the issue for me.

**Comment by LuKePicci** [comment]
Yup, thank you for reminding me the existence of upPASTE, will commit a dumb fix this issue adding the missing exports where needed for now. I will probably do a rework in order to avoid all this exports in future.

**Comment by papampi** [comment]
@Draco-Falcon 
Are you sure tempcontrol and watchdog are starting in guake?
There is no command to start them in guake.
When local is set, they start in screen and a tail will show the output in guake.

**Comment by LuKePicci** [comment]
Got it, 3main@362, upPASTE runs in guake, then in upPASTE@45/56 3main is directly launched instead of being killed letting 2unix (where NVOC is set) to reinit 3main correctly.
