### ISSUE TITLE
WTM_SWITCHER output_dir error

### ISSUE THREAD

**Issue by papampi** [papampi/nvOC_by_fullzero#50]
Tried to test the latest wtm switcher python and it gives me this error:

```
m1@m1-desktop-101:~$ python2.7 test_wtm 
Traceback (most recent call last):
  File "test_wtm", line 32, in <module>
    outputDir=cfg["output_dir"]
KeyError: 'output_dir'
```

**Comment by LuKePicci** [comment]
What is the content of WTM.json? Have you passed the full absolute path to that json as first argument?

Should be something like `python2.7 WTM_SWITCHER /path/to/WTM.json`

**Comment by papampi** [comment]
Content of WTM.json is created by 3main.
tried again with full path:

```
m1@m1-desktop-101:~$ python2.7 /home/m1/test_wtm /home/m1/WTM.json 
Traceback (most recent call last):
  File "/home/m1/test_wtm", line 32, in <module>
    outputDir=cfg["output_dir"]
KeyError: 'output_dir'

```

**Comment by LuKePicci** [comment]
Check if your 3main revision is recent enough, at some point in time 3main started writing also that key, if you have no output_dir in the json maybe you're using an old 3main


3main in 19-2.1 branch does it at line 469

**Comment by papampi** [comment]
OK, didnt noticed its been added to 3main.
