### ISSUE TITLE
Unified watchdog and temp control

### ISSUE THREAD

**Issue by papampi** [papampi/nvOC_by_fullzero#54]
@leenoox Had an idea long ago for a unified watchdog and tempcontrol 
I think we can have it for the cases that use both and reduce nvidia-smi calls which both scripts use it.
Something like:
```
if [ $MINER_WATCHDOG == "YES" && $MINER-TEMPCONTROL == "YES" ]
then
HCD="${NVOC}/7watchdog_tempcontrol"
```

Any ideas ?

**Comment by LuKePicci** [comment]
I think those two jobs should remain separate, but the watchdog could definitely read values from tempcontrol output instead of querying nvidia-smi again.

**Comment by papampi** [comment]
That would be great to make it read from tempcontrol and make the query for itself if temocontrol was disabled

**Comment by papampi** [comment]
A watchdog PR is already open, you gonna push to it or merge it and make a new PR ?

**Comment by LuKePicci** [comment]
Maybe I can push to it, but won't do any coding until I got a nice idea to do it with reasonably ease. If someone else already has any nice idea about how to do that, please don't wait me.

**Comment by papampi** [comment]
Since parent can export variable to its children may be we can run nvidia-smi in the last 3main empty loop and export the variables to its children watchdog and tempcontrol?

**Comment by LuKePicci** [comment]
Nope, the environment is forked with the process memory when executed, everything assigned and exported after is not inherited.
