### ISSUE TITLE
Apply GPU0 OC 2 times

### ISSUE THREAD

**Issue by papampi** [papampi/nvOC_by_fullzero#55]
On 3main restart it apply OC to GPU0 2 times, is this normal? 
Also there is a break after GPU1, I think it expand with more cards, I only tested on 3 card rig.

```
  Attribute 'GPUGraphicsClockOffset' (m1-desktop-100:0[gpu:0]) assigned value 150.

  Attribute 'GPUMemoryTransferRateOffset' (m1-desktop-100:0[gpu:0]) assigned value 800.

  Attribute 'GPUGraphicsClockOffset' (m1-desktop-100:0[gpu:0]) assigned value 150.

  Attribute 'GPUMemoryTransferRateOffset' (m1-desktop-100:0[gpu:0]) assigned value 800.

  Attribute 'GPUGraphicsClockOffset' (m1-desktop-100:0[gpu:1]) assigned value 150.

  Attribute 'GPUMemoryTransferRateOffset' (m1-desktop-100:0[gpu:1]) assigned value 800.



  Attribute 'GPUGraphicsClockOffset' (m1-desktop-100:0[gpu:2]) assigned value 150.

  Attribute 'GPUMemoryTransferRateOffset' (m1-desktop-100:0[gpu:2]) assigned value 800.

```

```
m1@m1-desktop-100:~$./nvOC gpuinfo
ID  |  PS  |  T°  |  FAN  |  LOAD  |  POWER / LIMIT / MAX  |  GPUCLOCK  |  MEMCLOCK  |  VENDOR - MODEL
0   |  P2  |  58  |  50   |  98    |  98 / 100 / 100       |  1556      |  4201      |  ASUS - GeForce GTX 1070
1   |  P0  |  53  |  50   |  100   |  78 / 78 / 78         |  1506      |  4404      |  GIGABYTE - P106-100
2   |  P0  |  60  |  50   |  93    |  79 / 78 / 78         |  1493      |  4404      |  GIGABYTE - P106-100

```

**Comment by LuKePicci** [comment]
Which is the value of the TI variable at that point?

Inviato dal mio telefono Windows 10

Da: Payam Nab
Inviato: giovedì 10 maggio 2018 15:26
A: papampi/nvOC_by_fullzero_Community_Release
Cc: Luca Piccirillo; Assign
Oggetto: [papampi/nvOC_by_fullzero_Community_Release] Aply GPU0 OC 2 times(#55)

On 3main restart it apply OC to GPU0 2 times, is this normal?
Also there is a break after GPU1, I think it expand with more cards, I only tested on 3 card rig.
  Attribute 'GPUGraphicsClockOffset' (m1-desktop-100:0[gpu:0]) assigned value 150.

  Attribute 'GPUMemoryTransferRateOffset' (m1-desktop-100:0[gpu:0]) assigned value 800.

  Attribute 'GPUGraphicsClockOffset' (m1-desktop-100:0[gpu:0]) assigned value 150.

  Attribute 'GPUMemoryTransferRateOffset' (m1-desktop-100:0[gpu:0]) assigned value 800.

  Attribute 'GPUGraphicsClockOffset' (m1-desktop-100:0[gpu:1]) assigned value 150.

  Attribute 'GPUMemoryTransferRateOffset' (m1-desktop-100:0[gpu:1]) assigned value 800.



  Attribute 'GPUGraphicsClockOffset' (m1-desktop-100:0[gpu:2]) assigned value 150.

  Attribute 'GPUMemoryTransferRateOffset' (m1-desktop-100:0[gpu:2]) assigned value 800.

**Comment by papampi** [comment]
How do I check TI value ?

**Comment by papampi** [comment]
Will add an echo in 3main to check it

**Comment by LuKePicci** [comment]
Put an ‘echo $TI’ before the call to nvidia-settings

Inviato dal mio telefono Windows 10

Da: Payam Nab
Inviato: giovedì 10 maggio 2018 15:31
A: papampi/nvOC_by_fullzero_Community_Release
Cc: Luca Piccirillo; Assign
Oggetto: Re: [papampi/nvOC_by_fullzero_Community_Release] Apply GPU0 OC 2times (#55)

How do I check TI value ?

**Comment by papampi** [comment]
TI: 2 3

**Comment by papampi** [comment]
My test rig is a mix of 1x1070 + 2xP106
So its the 2nd argument in 
```
  if [ $___1050_or_1050ti == "YES" ]
  then
    TI="2"
    if [ $NORMAL == "YES" ]
    then
      TI="2 3"
    fi
  fi

```

And we have these at start of 3main

```
if grep -q -E 'P106|P104|P102' /tmp/tempa; then
  ___1050_or_1050ti="YES"
  P10X_100="YES"
fi

if grep -q -E '1060|1070|1080' /tmp/tempa; then
  NORMAL="YES"
fi
```

**Comment by LuKePicci** [comment]
As expected, this means that your gpu0 is of a different kind with respect to the other two. The TI workaround is triggered, therefore each gpu gets overclocked for both perf level 2 and 3. Your gpu0 seems to be a ‘normal’ one, with both perf level 2 and 3 clocks editable, therefore you see two times there n the output. I guess the other two are p10x cards, or 1050/ti

Inviato dal mio telefono Windows 10

Da: Payam Nab
Inviato: giovedì 10 maggio 2018 15:34
A: papampi/nvOC_by_fullzero_Community_Release
Cc: Luca Piccirillo; Assign
Oggetto: Re: [papampi/nvOC_by_fullzero_Community_Release] Apply GPU0 OC 2times (#55)

TI: 2 3

**Comment by LuKePicci** [comment]
For the ske of it my guessing was before reading your last message….. 😅 

Inviato dal mio telefono Windows 10

Da: Payam Nab
Inviato: giovedì 10 maggio 2018 15:37
A: papampi/nvOC_by_fullzero_Community_Release
Cc: Luca Piccirillo; Assign
Oggetto: Re: [papampi/nvOC_by_fullzero_Community_Release] Apply GPU0 OC 2times (#55)

My test rig is a mix of 1x1070 + 2xP106
So its the 2nd argument in
  if [ $___1050_or_1050ti == "YES" ]
  then
    TI="2"
    if [ $NORMAL == "YES" ]
    then
      TI="2 3"
    fi
  fi

And we have these at start of 3main
if grep -q -E 'P106|P104|P102' /tmp/tempa; then
  ___1050_or_1050ti="YES"
  P10X_100="YES"
fi

if grep -q -E '1060|1070|1080' /tmp/tempa; then
  NORMAL="YES"
fi

**Comment by papampi** [comment]
Yup, thought so ...
