### ISSUE TITLE
${NVOC}/nvoc_logs location

### ISSUE THREAD

**Issue by papampi** [papampi/nvOC_by_fullzero#56]
We should change nvoc_logs location in screenrc config files
from:
`${NVOC}/nvoc_logs`
to:
`/home/m1/nvoc_logs 
`
As its a tmpfs location added in fstab.
`tmpfs /home/m1/nvoc_logs tmpfs defaults,noatime,nosuid,nodev,noexec,mode=1777,size=512M 0 0
`
If users use default /home/m1 location there is no problem, but if use other locations, it will write logs to HDD/SSD/USB and lower device lifespan. 

@LuKePicci , you got better idea for this?

**Comment by LuKePicci** [comment]
Just execute in 3main after (eventual) log folder creation:

`sudo mount -t tmpfs -o defaults,noatime,nosuid,nodev,noexec,mode=1777,size=512M nvoc_logs_$(echo ${NVOC} | shasum | head -c 6) ${NVOC}/nvoc_logs`

**Comment by LuKePicci** [comment]
Remember to also remove the old existing line from fstab if you're creating a new nvOC image.
