### ISSUE TITLE
Telegram messages not sent when they become too long

### ISSUE THREAD

**Issue by LuKePicci** [papampi/nvOC_by_fullzero#63]
When the message becomes too long the call to telegram api starts to fail and no more messages are sent. I'd suggest to either send a shorter tail of logs while also truncating in any case the message if too long.

**Comment by papampi** [comment]
Try with a value more than 5 for curl max timeout (-m 5)  and see how it goes

**Comment by LuKePicci** [comment]
That's not a timeout problem, I have seen the tgapi response with the error message complaining about message length.

**Comment by papampi** [comment]
Then cut it down ...
Telegram is blocked in my country and I cant use it anymore ...

**Comment by LuKePicci** [comment]
Fixed into #78
