### ISSUE TITLE
GPU_OFFSET question 

### ISSUE THREAD

**Issue by papampi** [papampi/nvOC_by_fullzero#64]
Regarding the two ALGO_SPECIFIC_with_GPU_OFFSET and GLOBAL_with_GPU_OFFSET modes, does this how they work?
ALGO_SPECIFIC_with_GPU_OFFSET: Set Algo Specific values then add plus/minus values for individual GPUs 
And same for Global with offset ...

**Comment by LuKePicci** [comment]
Yes, exactly, the only other thing to be underlined it’s that if algo-specific values for an algo are missing, global values are used in place as a fallback. This way you only need to set algo-specific settings for algos you’d like to use different values from global ones. This was already like that before my changes. But it was not explicated.

Inviato dal mio telefono Windows 10

Da: Payam Nab
Inviato: lunedì 21 maggio 2018 11:29
A: papampi/nvOC_by_fullzero_Community_Release
Cc: Subscribed
Oggetto: [papampi/nvOC_by_fullzero_Community_Release] GPU_OFFSET question(#64)

Regarding the two ALGO_SPECIFIC_with_GPU_OFFSET and GLOBAL_with_GPU_OFFSET modes, does this how they work?
ALGO_SPECIFIC_with_GPU_OFFSET: Set Algo Specific values then add plus/minus values for individual GPUs
And same for Global with offset ...

**Comment by papampi** [comment]
So isn't it better to set all GPU_SPECIFIC values to blank to prevent misuse problems?

**Comment by LuKePicci** [comment]
We know, as script writers, that leaving those variables unset will be equivalent to a variable set to 0, but users may get confused easily. I'd rather keep all initialized to 0.

**Comment by sizzlephizzle** [comment]
I would still like to champion GPU discovery and a template per GPU
make/model.

Something simple like
if gpu = 1060, core=-200 me=900, power=76
if gpu = 1070, core=100 mem=700, power=110
etc etc

Can use the settings from buriedone just as a "runs well out of the box"
then users can tweak their own as time goes on, but immediately will be
working to a good standard (The above gets 22mh/250sols on a 3gb 1060 and
29.8mh/410sols on a 1070)

**Comment by LuKePicci** [comment]
If you think that a rig will likely be composed of a fixed set of (hopefully not mixed) gpus you'll quickly find how useless would be a chunk of code which always detect the gpu type and decides "optimal" oc values at runtime. Then you should also consider tthose values are "ggod for all" only as a starting point, then everybody should check each car for stability and eventually tweak configs. You would obtain the same effect by simply suggesting users to visit buriedone checking for what kind of OC their cards support.

**Comment by papampi** [comment]
Agree with Luke 
And as I said before we have seen the same manufacturers use different parts and that makes different OC values even for same cards from same company with different manufacturing patch
So if we nvOC going to set values for card types for sure it will cause so many problems

**Comment by papampi** [comment]
@LuKePicci , should I set salfter values to 0 as well, or just the uppercase oc values?

**Comment by LuKePicci** [comment]
All of them, since every policy equally applies to any kind of switchers.

**Comment by papampi** [comment]
Done in PR #60
