### ISSUE TITLE
nvOC syntax error: Restart command is broken

### ISSUE THREAD

**Issue by Alysko** [papampi/nvOC_by_fullzero#68]
> ./nvOC: line 217: syntax error near unexpected token `&&'
> ./nvOC: line 217: `        Stop() && Start()'

**Comment by sizzlephizzle** [comment]
Revert to my original method. nvOC stop && nvOC start

**Comment by LuKePicci** [comment]
There is a syntax error, should be `Start && Stop` without brackets. I also noticed you missed to add the restart command in both command switch at the bottom of the file and in the help message. I hope @papampi would like to fix it without having to open a new PR.

**Comment by papampi** [comment]
Should be fixed in https://github.com/papampi/nvOC_by_fullzero_Community_Release/commit/88683c31fea1d164f3479a67d6dad82e6928266f
