### ISSUE TITLE
Headless mode , p104, p102 issue

### ISSUE THREAD

**Issue by papampi** [papampi/nvOC_by_fullzero#69]
@doftorul posted this in discord:

setting HEADLESS_MODE has no effect
what i mean is, xorg gets regenerated after every reboot
i'll download the latest commits and try again, however, in its current state it does not work with p104 or P102
one important thing to note is the HEADLESS should not be forced upon the user
xorg should be generated using the intel graphic card as a renderer
and this will not affect in any way the p104 or P 102 cards
another thing of note is that the P104 and P102 cards use PerfMode 1 for overclocking
so in 3main the TI should be set 1 instead of 2 or 3
$TI
if i comment everything related to xorg or overclocking from 3main, it works as it should
generating the xorg.conf using:
sudo nvidia-xconfig -enable-all-gpus -cool-bits=28 --allow-empty-initial-configuration
and overclocking with
sudo DISPLAY=:0 XAUTHORITY=/var/run/lightdm/root/:0 nvidia-settings -a '[gpu:0]/GPUGraphicsClockOffset[1]=100' -a '[gpu:0]/GPUMemoryTransferRateOffset[1]=1200'
so, i think we need to rewrite the entire logic behind the testing of tempa for 1050, 1050 Ti, P106, P104, P102

**Comment by papampi** [comment]
@doftorul 
3main writes "XORG_UPDATED" to ${NVOC}/xorg_flag after updating xorg for headless mode, can you check and see if it exists or not?

**Comment by papampi** [comment]
3main command for headless mode is same as what you run manually :
`sudo nvidia-xconfig -a --enable-all-gpus --allow-empty-initial-configuration --cool-bits=28
`

**Comment by papampi** [comment]
PR #70

**Comment by LuKePicci** [comment]
@papampi as you reported in #55 you have two p10x cards which were getting overclocked by performance level 2. This means it's not always perf level 1 or 2.

**Comment by doftorul** [comment]
With P104 its always perf 1.

Tested on 20 rigs with 9 gpus each.

I can post pictures as well.

On other 20 P102 rigs with 8 cards i found that there's always perf 1 as
well

Querying nvidia-smi shows as well only perf mode 1 available and editable
for clocks and memory transfer rate offset.

**Comment by LuKePicci** [comment]
@papampi have two p106, maybe that's the difference.

**Comment by papampi** [comment]
Another mix rig of  1060 and  p106 with headless mode yes on 19-2.0 :

```
m1@m1-desktop-103:~$./nvOC gpuinfo

ID,VENDOR,MODEL,PSTATE,TEMP,FAN,UTILIZATION,POWER,POWERLIMIT,MAXPOWER,GPUCLOCK,MEMCLOCK
--------------------------------------------------------------------------------
0, ZOTAC, GeForce GTX 1060 6GB, P2, 60, 45, 99, 78.42, 78.00, 140.00, 1721, 3802
1, GIGABYTE, P106-100, P0, 66, 45, 100, 76.32, 78.00, 140.00, 1240, 4276
2, GIGABYTE, P106-100, P0, 63, 45, 100, 79.17, 78.00, 140.00, 1290, 4276
3, ZOTAC, GeForce GTX 1060 6GB, P2, 63, 45, 100, 77.99, 78.00, 140.00, 1695, 3802
4, ZOTAC, GeForce GTX 1060 6GB, P2, 68, 45, 100, 76.74, 78.00, 140.00, 1670, 3802
5, GIGABYTE, P106-100, P0, 62, 45, 100, 78.39, 78.00, 140.00, 1379, 4276
6, GIGABYTE, P106-100, P0, 66, 45, 99, 78.37, 78.00, 140.00, 1341, 4276
7, GIGABYTE, P106-100, P0, 69, 45, 97, 78.32, 78.00, 140.00, 1215, 4276
8, MSI, P106-100, P0, 59, 45, 100, 76.62, 78.00, 140.00, 1328, 4276
9, ZOTAC, GeForce GTX 1060 6GB, P2, 60, 45, 100, 78.76, 78.00, 140.00, 1746, 3802
10, GIGABYTE, P106-100, P0, 57, 45, 100, 78.14, 78.00, 140.00, 1354, 4276
11, ZOTAC, GeForce GTX 1060 6GB, P2, 62, 45, 100, 79.05, 78.00, 140.00, 1721, 3802
```

**Comment by papampi** [comment]
@doftorul can you please test 3main from #70 and see how it goes?

**Comment by papampi** [comment]
And did you checked "XORG_UPDATED" in ${NVOC}/xorg_flag ?

**Comment by doftorul** [comment]
Testing in 1 hr ...

**Comment by papampi** [comment]
Fixed with #70 ?

**Comment by doftorul** [comment]
Testing it now.

I had to push the commit since i don't know how to work with version control...

In the meanwhile, testing for perfmode on both p104 and p102, different batches, different vendors, i get always this:

sudo DISPLAY=:0 XAUTHORITY=/var/run/lightdm/root/:0 nvidia-settings -q '[gpu:0]/GPUPerfModes'

  Attribute 'GPUPerfModes' (p104-04:0[gpu:0]): perf=0, nvclock=139, nvclockmin=139, nvclockmax=607, nvclockeditable=1,
  memclock=405, memclockmin=405, memclockmax=405, memclockeditable=1, memTransferRate=810, memTransferRatemin=810,
  memTransferRatemax=810, memTransferRateeditable=1 ; perf=1, nvclock=139, nvclockmin=139, nvclockmax=2050, nvclockeditable=1,
  memclock=5805, memclockmin=5805, memclockmax=5805, memclockeditable=1, memTransferRate=11610, memTransferRatemin=11610,
  memTransferRatemax=11610, memTransferRateeditable=1

So perfmode 1 is confirmed for p104 and P 102

**Comment by papampi** [comment]
Ok, thought you tested , then approved it
Will revert it back if needed
May need to make more changes
