### ISSUE TITLE
README mistake on git update

### ISSUE THREAD

**Issue by cbesot** [papampi/nvOC_by_fullzero#76]
[https://github.com/papampi/nvOC_by_fullzero_Community_Release/wiki/nvOC-19-2.1-beta-testing](https://github.com/papampi/nvOC_by_fullzero_Community_Release/wiki/nvOC-19-2.1-beta-testing)

> Update nvOC to latest commit:
> cd /home/m1/NVOC
> git pull origin 19-2.1

Should be cd /home/m1/NVOC/testing because it's the path you choose in git clone.

**Comment by papampi** [comment]
Thanks mate
Fixed it
