### ISSUE TITLE
Not the right algo

### ISSUE THREAD

**Issue by Alysko** [papampi/nvOC_by_fullzero#87]
https://github.com/papampi/nvOC_by_fullzero_Community_Release/blob/92afa9e4cfa2d5ead5c91362d4c64b121b5a0d4a/1bash#L1444-L1449

Hi there!
I think there's a problem here.
First of all, "Monero" is not defined elsewhere. Next, XMR (so, Monero) is not PHI.

**Comment by Alysko** [comment]
Same here with MPH_MYR-GR: https://github.com/papampi/nvOC_by_fullzero_Community_Release/blob/92afa9e4cfa2d5ead5c91362d4c64b121b5a0d4a/1bash#L1462-L1467

**Comment by papampi** [comment]
#90
