### ISSUE TITLE
NICE_"some algo" not working correctly

### ISSUE THREAD

**Issue by pegga** [papampi/nvOC_by_fullzero#88]
Hi guys,

1) NICE_EQUIHASH, ETHASH, etc are not working for me. Miner keeps restarting. Log shown invalid parameters for miner (actually epty parameters). It helped me to unify NICE_... and NICE-... which are used in 1bash and 0miner. After change from NICE-... to NICE_... miners are working well (some).

2) NICE_... mining options are not working together with WTM_SWITCHING. I assume there is problem with parsing JSON for these, sice it does not contain directly name of the coin. I have to check WTM_SWITCHING option and how it works. 

3) TPccminer does not work for me for lyra2rev2. I tried NICE_LYRA2REV2. Miner keeps restarting without much mentioned in screen log. Tried ASccminer and this one seems to work well. Any suggestions on what to check?

**Comment by LuKePicci** [comment]
WTM uses NICE-... to identify algorithms, so anything in nvOC should refer to NICE-... I've not looked into nicehash support but if you are able to understand why using NICE_ instead of NICE- resolve your issue number 1) please report. Meanwhile @papampi should take care of this.

**Comment by pegga** [comment]
as far as I understand, there is mixture of - and _ which causes problems. Coin is called NICE-..., but params for miner like
NICE_EQUIHASH_POOL="equihash.eu.nicehash.com"
NICE_EQUIHASH_PORT="3357"
NICE_EQUIHASH_WORKER="$WORKERNAME"
use _ as you can see. This is problem when composing variable names in 0miner. Of course it can be unified to NICE-... too. Why not. I will try to do it tomorrow.

**Comment by sizzlephizzle** [comment]
For the record, I did preach that NICE- is not callable in bash. It breaks
the variable.

To fix, I think you will need to find any reference to NICE- and replace
with NICE_ Except in MPH where the conversion to NICE- Should occur.

Siz

**Comment by papampi** [comment]
@pegga 
Can you please check and test NICE fix PR #89 and see if it works or not
As you noticed there was a mix settings of NICE- and NICE_, they should be fixed.

**Comment by papampi** [comment]
It looks like wtm switcher should work too

```
BTC PRICE: 7691.0 USD
NICE_ETHASH 3.81 USD
NICE_CRYPTONIGHTV7 3.53 USD
ZCL 3.42 USD
NICE_EQUIHASH 3.18 USD
ZEN 3.06 USD
XVG 3.04 USD
BTX 2.92 USD
VTC 2.88 USD
KMD 2.88 USD
EXP 2.84 USD
MUSIC 2.82 USD
BSD 2.56 USD
GBX 1.67 USD
VIVO 1.52 USD
New profits
NICE_ETHASH: 103 %
NICE_CRYPTONIGHTV7: 96 %
ZCL: 93 %
NICE_EQUIHASH: 86 %
ZEN: 83 %
XVG: 83 %
BTX: 79 %
VTC: 78 %
KMD: 78 %
EXP: 77 %
MUSIC: 77 %
BSD: 70 %
GBX: 45 %
VIVO: 41 %


```

**Comment by LuKePicci** [comment]
@sizzlephizzle so it is mph and not wtm which uses nice- instead of nice_ ?

**Comment by papampi** [comment]
lol ... 
mph not use nice at all ... I'm sure it was a mistake.

**Comment by LuKePicci** [comment]
Sure... that was quite strange tbh

**Comment by sizzlephizzle** [comment]
Yeah sorry, WTM not mph. Knew it was one of the three letter acronyms haha.

Sorry folks.

Still, bash/shell cannot call $NICE-Anything because the hypen breaks the
variable.

**Comment by LuKePicci** [comment]
I think you can use ${var-name} to fix this

Da: sizzlephizzle
Inviato: giovedì 7 giugno 2018 00:48
A: papampi/nvOC_by_fullzero_Community_Release
Cc: Luca Piccirillo; Comment
Oggetto: Re: [papampi/nvOC_by_fullzero_Community_Release] NICE_"some algo" notworking correctly (#88)

Yeah sorry, WTM not mph. Knew it was one of the three letter acronyms haha.

Sorry folks.

Still, bash/shell cannot call $NICE-Anything because the hypen breaks the
variable.

**Comment by papampi** [comment]
But if wtm works with PR #89, wouldn't it be better to all be the same with underscore?
I can't test NICE, so if anyone can test please do.

**Comment by LuKePicci** [comment]
> But if wtm works with PR #89, wouldn't it be better to all be the same with underscore?

Of course

**Comment by papampi** [comment]
@pegga PR #89 is waiting for your test and approval, 
Please check and let us know.

**Comment by pegga** [comment]
it works!

any comments on "TPccminer does not work for me for lyra2rev2" - I tried NICE_LYRA2REV2 to be specific

**Comment by papampi** [comment]
Whats the error?
Whats the miner start command line?

**Comment by pegga** [comment]
SCREEN -c /home/m1/NVOC/testing/screenrc-miner -dmSL miner /home/m1/NVOC/testing/miners/TPccminer/ccminer -a lyra2v2 -o stratum+tcp://lyra2rev2.eu.nicehash.com:3347 -u MYBTCADDRESS.102 -p x -i

...MYBTCADDRESS is substitute for my address
I cannot even see miner start. this the only thing I see in the log file. Is there some more to check? I am in remote connection right now.

**Comment by LuKePicci** [comment]
Try running TPccminer directly with the same command line you reported but outside of screen, see what happens.

**Comment by papampi** [comment]
Run it from a guake tab and check the error message
/home/m1/NVOC/testing/miners/TPccminer/ccminer -a lyra2v2 -o stratum+tcp://lyra2rev2.eu.nicehash.com:3347 -u MYBTCADDRESS.102 -p x -i
