### ISSUE TITLE
Miner fails, followed by 3 attempts to restart (the miner) but still fails and forces a system reboot

### ISSUE THREAD

**Issue by loumposa** [papampi/nvOC_by_fullzero#98]
Hi,

If the miner fails, the system tries to restart 3main  but doesn't restart. 
This process is repeated 3 times unsuccesfully and then the system is rebooting and rig continues as expecting.
If during the recycling (of the 3 attempts) of restarting 3main I kill the process with nvOC stop, processing stops, then i execute nvOC start and the miner restarts successfully.
Seems that I'm facing a bug/defects somewhere here. Any advise will be really helpfull

Cheers
:)

**Comment by LuKePicci** [comment]
Please, give us some information about your setup, which miner, mode, coin, nvOC version, install directory, gnome-terminal output, logs, anything.

**Comment by loumposa** [comment]
Setup
1x1070Ti
12x1080Ti
-----------
LAUNCHING:  MINER   
 SCREEN -dmSL miner /home/m1/eth/claymore/latest/ethdcrminer64 -epool eth-eu1.nanopool.org:9999 -ewal 0xC8d4b2e560094fe60CA42340726866D18CA94c18/063/ -epsw x -mode 1 -dbg -1

--------------
nvOC 19-2.0
------------------

Watchdog log

WARNING: Thu Jun 14 23:24:39 BST 2018 - Problem found: See diagnostics below: 
Percent of GPUs bellow threshold: 100 %
name, pstate, temperature.gpu, fan.speed [%], utilization.gpu [%], power.draw [W], power.limit [W]
GeForce GTX 1070 Ti, P2, 56, 35 %, 1 %, 48.78 W, 125.00 W
GeForce GTX 1080 Ti, P2, 58, 35 %, 0 %, 63.22 W, 210.00 W
GeForce GTX 1080 Ti, P2, 59, 35 %, 0 %, 63.42 W, 160.00 W
GeForce GTX 1080 Ti, P2, 54, 35 %, 0 %, 62.19 W, 160.00 W
GeForce GTX 1080 Ti, P2, 57, 35 %, 0 %, 61.35 W, 210.00 W
GeForce GTX 1080 Ti, P2, 50, 35 %, 0 %, 65.41 W, 160.00 W
GeForce GTX 1080 Ti, P2, 56, 35 %, 0 %, 64.17 W, 210.00 W
GeForce GTX 1080 Ti, P2, 58, 35 %, 0 %, 62.32 W, 210.00 W
GeForce GTX 1080 Ti, P2, 54, 35 %, 0 %, 81.26 W, 160.00 W
GeForce GTX 1080 Ti, P2, 50, 35 %, 0 %, 71.09 W, 160.00 W
GeForce GTX 1080 Ti, P2, 60, 35 %, 49 %, 72.35 W, 160.00 W
GeForce GTX 1080 Ti, P0, 55, 35 %, 0 %, 64.46 W, 210.00 W
GeForce GTX 1080 Ti, P8, 51, 35 %, 0 %, 12.28 W, 160.00 W
[0m[1;32mGPU #2: GeForce GTX 1080 Ti, 11178 MB available, 28 compute units, capability: 6.1  (pci bus 6:0:0)
[0m[1;32mGPU #3: GeForce GTX 1080 Ti, 11178 MB available, 28 compute units, capability: 6.1  (pci bus 8:0:0)
[0m[1;32mGPU #4: GeForce GTX 1080 Ti, 11178 MB available, 28 compute units, capability: 6.1  (pci bus 9:0:0)
[0m[1;32mGPU #5: GeForce GTX 1080 Ti, 11178 MB available, 28 compute units, capability: 6.1  (pci bus 10:0:0)
[0m[1;32mGPU #6: GeForce GTX 1080 Ti, 11178 MB available, 28 compute units, capability: 6.1  (pci bus 11:0:0)
[0m[1;32mGPU #7: GeForce GTX 1080 Ti, 11178 MB available, 28 compute units, capability: 6.1  (pci bus 12:0:0)
[0m[1;32mGPU #8: GeForce GTX 1080 Ti, 11178 MB available, 28 compute units, capability: 6.1  (pci bus 13:0:0)
[0m[1;32mGPU #9: GeForce GTX 1080 Ti, 11178 MB available, 28 compute units, capability: 6.1  (pci bus 14:0:0)
[0m[1;32mGPU #10: GeForce GTX 1080 Ti, 11178 MB available, 28 compute units, capability: 6.1  (pci bus 15:0:0)
[0m[1;32mGPU #11: GeForce GTX 1080 Ti, 11178 MB available, 28 compute units, capability: 6.1  (pci bus 16:0:0)
[0m[1;32mGPU #12: GeForce GTX 1080 Ti, 11178 MB available, 28 compute units, capability: 6.1  (pci bus 17:0:0)
[0m[1;32mTotal cards: 13 
[0m
You can use "+" and "-" keys to achieve best ETH speed, see "FINE TUNING" section in Readme for details.

CRITICAL: Thu Jun 14 23:24:39 BST 2018 - GPU Utilization is too low: restarting 3main...


WARNING: Thu Jun 14 23:27:21 BST 2018 - Problem found: See diagnostics below: 
Percent of GPUs bellow threshold: 100 %
name, pstate, temperature.gpu, fan.speed [%], utilization.gpu [%], power.draw [W], power.limit [W]
GeForce GTX 1070 Ti, P8, 36, 35 %, 0 %, 13.38 W, 125.00 W
GeForce GTX 1080 Ti, P8, 37, 35 %, 0 %, 11.41 W, 210.00 W
GeForce GTX 1080 Ti, P8, 31, 35 %, 0 %, 9.26 W, 160.00 W
GeForce GTX 1080 Ti, P8, 41, 35 %, 0 %, 11.06 W, 160.00 W
GeForce GTX 1080 Ti, P8, 35, 35 %, 0 %, 10.60 W, 210.00 W
GeForce GTX 1080 Ti, P8, 35, 35 %, 0 %, 11.78 W, 160.00 W
GeForce GTX 1080 Ti, P8, 36, 35 %, 0 %, 12.24 W, 210.00 W
GeForce GTX 1080 Ti, P8, 35, 35 %, 0 %, 10.80 W, 210.00 W
GeForce GTX 1080 Ti, P8, 38, 35 %, 0 %, 11.73 W, 160.00 W
GeForce GTX 1080 Ti, P8, 36, 35 %, 0 %, 11.25 W, 160.00 W
GeForce GTX 1080 Ti, P8, 32, 35 %, 0 %, 10.61 W, 160.00 W
GeForce GTX 1080 Ti, P8, 34, 35 %, 0 %, 11.18 W, 210.00 W
GeForce GTX 1080 Ti, P8, 38, 35 %, 0 %, 11.04 W, 160.00 W
[0m[1;32mGPU #2: GeForce GTX 1080 Ti, 11178 MB available, 28 compute units, capability: 6.1  (pci bus 6:0:0)
[0m[1;32mGPU #3: GeForce GTX 1080 Ti, 11178 MB available, 28 compute units, capability: 6.1  (pci bus 8:0:0)
[0m[1;32mGPU #4: GeForce GTX 1080 Ti, 11178 MB available, 28 compute units, capability: 6.1  (pci bus 9:0:0)
[0m[1;32mGPU #5: GeForce GTX 1080 Ti, 11178 MB available, 28 compute units, capability: 6.1  (pci bus 10:0:0)
[0m[1;32mGPU #6: GeForce GTX 1080 Ti, 11178 MB available, 28 compute units, capability: 6.1  (pci bus 11:0:0)
[0m[1;32mGPU #7: GeForce GTX 1080 Ti, 11178 MB available, 28 compute units, capability: 6.1  (pci bus 12:0:0)
[0m[1;32mGPU #8: GeForce GTX 1080 Ti, 11178 MB available, 28 compute units, capability: 6.1  (pci bus 13:0:0)
[0m[1;32mGPU #9: GeForce GTX 1080 Ti, 11178 MB available, 28 compute units, capability: 6.1  (pci bus 14:0:0)
[0m[1;32mGPU #10: GeForce GTX 1080 Ti, 11178 MB available, 28 compute units, capability: 6.1  (pci bus 15:0:0)
[0m[1;32mGPU #11: GeForce GTX 1080 Ti, 11178 MB available, 28 compute units, capability: 6.1  (pci bus 16:0:0)
[0m[1;32mGPU #12: GeForce GTX 1080 Ti, 11178 MB available, 28 compute units, capability: 6.1  (pci bus 17:0:0)
[0m[1;32mTotal cards: 13 
[0m
You can use "+" and "-" keys to achieve best ETH speed, see "FINE TUNING" section in Readme for details.

CRITICAL: Thu Jun 14 23:27:22 BST 2018 - GPU Utilization is too low: restarting 3main...

**Comment by sizzlephizzle** [comment]
LOCALORREMOTE is set to remote? If so, switch to local.

Siz

**Comment by loumposa** [comment]
LOCAL is the setting in use

**Comment by LuKePicci** [comment]
Try to get it running with new nvOC 2.1 branch, I think you have some watchdog checking interval issues. Do you always had this problem or it started recently after you changed hardware/miner?

**Comment by loumposa** [comment]
I think i always had this problem and only started noticing the restart/reboots. HW/Miner has always been the same

**Comment by LuKePicci** [comment]
Ok, so you definitely have to switch to nvOC 2.1, I'm not able to help you on the old version, lot of things changed that could help you.

**Comment by loumposa** [comment]
I think you are right - moving on should be good. Its not a big issue for now as when the issues occurs I'm losing about 5 mins before the rig reboots and starts over again.
Can the team share a guestimate on when the image for 2.1 would be released
I would prefer a clean install instead of adding on top of 2.0 as i'm still in a learning curve here

**Comment by LuKePicci** [comment]
For sure after the next nvOC will be mature enough. New nVidia GPUs are coming so maybe we would like to release n image with already updated nVidia driver if needed. Probably, given the new way of getting nvOC updates it could be the last definitive image, in the sense that any update will then be applied on top of it, to avoid you reimaging all the times. We were also discussing on letting nvOC images directly getting from git repository the latest stable version on first startup, so I would suggest you to try the guide you find here in the wiki to let the new version running on your current image, is very easy, and IMHO even easier then reimaging.

**Comment by loumposa** [comment]
what i was hoping to do is get a new ssd, burn the image, remove the old ssd and plug the new image in. Then config would only take a couple mins. I'm kind of hesitating to install a beta version. If the new stable image of 2.1 can update nvOC components without having to manually execute that would a great step forward.

**Comment by papampi** [comment]
Try with adding a "-retrydelay 5"  to claymore optional arguments see how it goes

**Comment by loumposa** [comment]
As a newbie apologies for the silly question but in which file do i need to add this argument into?

**Comment by papampi** [comment]
You have it in 1bash after ETH worker, address, pool, port
ETH_EXTENSION_ARGUMENTS=" -retrydelay 5"    # add any additional Claymore miner arguments here

**Comment by loumposa** [comment]
just added the argument - will keep on monitoring and advise back :)

**Comment by loumposa** [comment]
i've been running 7 hours now no - issues....

Another question - I'm building a new rig - got everything in place - i've also downloaded the 19-2.0 image - what is the easier way to burn it on an SSD? i will be able to experiment and upgrade to 2.1 :)

**Comment by LuKePicci** [comment]
I'm sorry but this is not the place where to ask those kind of questions, please use the forum instead. You can also find lot of information regarding that procedure in the opening post

Now closing this issue since it is probably get fixed by different watchdog timing on the newer 2.1+ version. Will re-open in case it's not.
